bluesky/ophyd

ophyd/controls/positioner.py
ophyd/controls/signal.py

Added quotes round string in __str__ method so this can be used to create the object.

ENH : Added quotes for __str__ method on EpicsMotor

---

ophyd/userapi/cli_api.py
ophyd/userapi/scan_api.py

Fixed spelling mistake (oops) and also added check for None to position print in command line API

BUG: Fixed bugs with screen printing

---

ophyd/runengine/runengine.py

- Required by NSLS-II/metadataStore#86

API: Fix mds api

---

ophyd/runengine/runengine.py

insert_end_run -> insert_run_end
insert_begin_run -> insert_run_start
sundry variable/arg name changes

API : change begin/end event names

---

ophyd/runengine/runengine.py

Cousin pr to NSLS-II/metadatastore#90

MNT: Rename metadataStore -> metadatastore

---

ophyd/userapi/scan_api.py

I should really learn to call things words I can spell.........

BUG : Fixed name of logbook in count

---

ophyd/session/sessionmgr.py

Patch against #68.
Please test.

BUG: better scan_id persistence.

---

ophyd/runengine/runengine.py
ophyd/userapi/scan_api.py

Rebased by @ericdill , replaces #87

Move scans to logging

---

ophyd/controls/ophydobj.py
ophyd/runengine/runengine.py

Three critical bugs:
* One that looks like a merge failure
* Two related to keys in the data payload not being in the list of detectors.
While we were here, we also fixed logging so that INFO-level logging gives the output desired. We added a couple lines at @cmazzoli's request to print time, uid, and scan ID at the top of the ophyd output.

HOTFIX: Ophyd was broken.

---

ophyd/runengine/runengine.py

Clean up RunEngine a bit

---

ophyd/controls/ophydobj.py
ophyd/runengine/runengine.py
ophyd/userapi/cli_api.py
ophyd/userapi/scan_api.py

I'm lazy, so here's one PR for a few different things:
* Remove annoying (and expected) callback exception messages
* Some MDS fixes in here (from @ericdill) 
* wh_pos uses PrettyTable (@ericdill?)
* Some useful debug messages to figure out what exactly is going on with the scan/runengine thing
* Last but not least, fixes ctrl-c handling in the run engine (now that we have two replacement ones, of course...)

Ctrl-C fix and a couple other things

---

conda-recipe/meta.yaml

A missing dependency from  #146 ?

BLD: missing runtime dependency on filestore

---

ophyd/commands.py
ophyd/controls/positioner.py

Looks like this now:
```python
[[OPHYD_DEV]] In [1]: wh_pos()
+------------+---------------+--------------+--------------+
| Positioner |         Value |    Low Limit |   High Limit |
+------------+---------------+--------------+--------------+
| vx         |     -98.52000 |   -140.00000 |   -140.00000 |
| vy         |    2896.12300 |   2800.00000 |   3000.00000 |
| vz         |      11.41000 |      0.00000 |      0.00000 |
| zpssx      |       INVALID | Disconnected | Disconnected |
| zpssy      |       INVALID | Disconnected | Disconnected |
| zpssz      |       INVALID | Disconnected | Disconnected |
+------------+---------------+--------------+--------------+
```

FIX: wh_pos with DisconnectedError

---

ophyd/controls/area_detector.py

The replaces #131.  ~~It is the same commits, just rebased to deal with a merge conflict.~~
@dchabot Please review this, it is high priority for XPD

Enh squash stack

---

ophyd/controls/positioner.py

[FIX] enforce completion detection

---

doc/source/OEP/OEP_001.rst

A document to help us with the AD refactor

DOC: start to draft first OEP on AD refactor

---

ophyd/__init__.py
ophyd/areadetector/base.py
ophyd/device.py
ophyd/epics_motor.py
ophyd/pseudopos.py
ophyd/pv_positioner.py
ophyd/scaler.py
tests/test_ophyddevice.py

one last change to the API before we deploy -- already cleared with @klauer (on GH in #190) and @dchabot (in person)

API: OphydDevice -> Device

---

.travis.yml
ophyd/device.py
ophyd/scaler.py
ophyd/signal.py
ophyd/utils/epics_pvs.py
tests/test_ophyddevice.py
tests/test_scaler.py
tests/test_signal.py
tests/test_utils.py

New configure

---

ophyd/signal.py

Make signal implement all required bluesky methods

---

ophyd/device.py

Since `stage` and `unstage` are defined on devices but not on signals, it is actually easy to recursively stage a device and its subdevices without instantiating lazy signals -- or even non-lazy signals.
As you can see, we don't have to make reference to the lazy attribute in this implementation, only the `Component.cls`.

PERF: Stage/unstage without instantiating signals needlessly.

---

ophyd/device.py
tests/test_ophyddevice.py

FIX: Check that class is not shadowing 'name'

---

ophyd/device.py
tests/test_ophyddevice.py

FIX: correctly recursively collect _sig_attrs

---

ophyd/areadetector/filestore_mixins.py
ophyd/areadetector/plugins.py
ophyd/areadetector/trigger_mixins.py
ophyd/device.py
ophyd/mca.py
ophyd/scaler.py

Needs tests. Work in progress for XPD deployment today.

FileStore variations

---

ophyd/commands.py

closes NSLS-II/Bug-Reports/#53

ENH: add extra message to log_pos

---

ophyd/areadetector/filestore_mixins.py
ophyd/device.py
ophyd/signal.py

Mostly stealing @danielballan thunder here but
```python
from ophyd import SimDetector
from ophyd.areadetector.plugins import ProcessPlugin, TIFFPlugin
from ophyd.areadetector.filestore_mixins import FileStoreBase, FileStoreTIFFSquashing, FileStoreIterativeWrite
from ophyd.areadetector.trigger_mixins import SingleTrigger
from ophyd.device import (Component as C)
import filestore.api as fs
import filestore.handlers
fs.register_handler('AD_HDF5', filestore.handlers.AreaDetectorHDF5Handler)
fs.register_handler('AD_TIFF', filestore.handlers.AreaDetectorTiffHandler)
prefix = 'XF:31IDA-BI{Cam:Tbl}'
class LocalTiff(TIFFPlugin, FileStoreTIFFSquashing, FileStoreIterativeWrite):
pass
class SquashingDet(SingleTrigger, SimDetector):
proc1 = C(ProcessPlugin, 'Proc1:')
tiff1 = C(LocalTiff, 'TIFF1:', …
```

tiff squashing

---

ophyd/areadetector/trigger_mixins.py

This is about done, but needs testing and probably bug-fix commits before being merged -- hopefully later today.

ENH: Build out MultiTrigger class, our new way to support detector-controlled dark frames

---

tests/test_mca.py

This test was poking at real hardware (don't do that!).

TST: don't touch real hardware!

---

ophyd/epics_motor.py
ophyd/ophydobj.py
ophyd/pv_positioner.py

Users should be able to rename their Device components.

REF: object name is now mutable

---

ophyd/device.py
tests/test_timeout.py

FIX: fix device timeouterror message to include attr + prefix

---

examples/config.py
examples/motor.py
ophyd/pseudopos.py

Cherry-picking commits from #209 at direction of @klauer

Mnt pseudo cp

---

ophyd/signal.py
ophyd/utils/epics_pvs.py
tests/coverage_full.sh
tests/test_areadetector.py
tests/test_signal.py
tests/test_utils.py

Adds `precision`, `units`, and other fields to the dict returned by `EpicsSignal.describe()`.

Flesh out Signal.describe

---

.travis.yml
ophyd/device.py

- _orginals_vals needs to be an ordered dict
- unstage child devices (in reverse order) before unstaging self

Fix: order issues in unstage

---

ophyd/areadetector/filestore_mixins.py
ophyd/device.py

Work from hot-fixes at XPD and CSX

Continuous acq

---

ophyd/areadetector/detectors.py
ophyd/areadetector/filestore_mixins.py

See commit messages for details.

FileStore refactors and hotfixes from CHX

---

ophyd/commands.py

Addresses #256. Only.
We need some dedicated tests to address the connected/disconnected edges.

FIX: absorb search over disconnected Positioner

---

ophyd/signal.py
tests/test_signal.py
tests/test_timestamps.py

FIX: non-automonitored EpicsSignal timestamps

---

ophyd/pseudopos.py

MNT: pass kwargs through pseudopositioner.set

---

ophyd/__init__.py
ophyd/device.py
ophyd/ophydobj.py
ophyd/utils/errors.py
tests/test_device.py

This, plus a forthcoming bluesky PR, solves the problem that #280 meant to solve, better. Thanks, @klauer.

Expose new 'root' attribute, pointing to ultimate ancestor

---

ophyd/areadetector/plugins.py

Fixes #289 
Confirmed with @hhslepicka

FIX: ROIPlugin shadowed PluginBase enable

---

circle.yml
ophyd/commands.py
ophyd/epics_motor.py
tests/test_epicsmotor.py
tests/test_positioner.py

ENH: Positioner/EpicsMotor Additions Partially Fix Issue: #273

---

ophyd/signal.py

FIX: make base Signal.get permissive

---

ophyd/device.py
ophyd/epics_motor.py
ophyd/ophydobj.py
ophyd/positioner.py
ophyd/pv_positioner.py

ENH: make report property cooperative

---

doc/source/area-detector.rst
doc/source/builtin-devices.rst
doc/source/positioners.rst
doc/source/signals.rst
ophyd/areadetector/cam.py
ophyd/areadetector/detectors.py
ophyd/device.py

(@ericdill or @danielballan) any thoughts on getting the restructured text in the dynamic device component dynamic default docstring displaying as intended? It comes out as squashed, unformatted text.
I think overall this is an improvement...

DOC: documentation updates

---

ophyd/epics_motor.py
ophyd/positioner.py
ophyd/pseudopos.py
ophyd/pv_positioner.py
ophyd/status.py
tests/test_epicsmotor.py
tests/test_positioner.py
tests/test_pseudopos.py
tests/test_pvpositioner.py

Re-added per-Positioner default timeouts, at the request of @tacaswell

ENH: Default timeout

---

ophyd/areadetector/base.py
ophyd/device.py

A minor tweak of #296. They look decent in both sphinx and the command line help now.

DOC: cleanup ADComponent docstrings

---

ophyd/areadetector/filestore_mixins.py

To make it clearer which level of the classes is responsible for
this attribute.

MNT: add self._fn to init

---

ophyd/__init__.py
ophyd/areadetector/trigger_mixins.py
ophyd/quadem.py
tests/test_quadem.py

Do not merge yet.
This provides support for quad electrometers (AH401/501, NSLS EM, Tegra, etc).
More tests and docs to follow.

WIP: add support for quadEM EPICS devices

---

ophyd/signal.py

API: relax `put` on soft Signal

---

tests/test_timestamps.py

Bad test (that I wrote) annoyingly causing other PRs to fail. Hopefully this will fail less frequently

FIX: timestamp test bugfix

---

ophyd/mca.py

Basically tested and working at HXN with DXP mercury. Could use verification at SRX as this redoes some of the classes there.

ENH: full DXP system base, mapping mode, Saturn and Mercury templates

---

ophyd/utils/__init__.py
ophyd/utils/paths.py
tests/test_utils.py

ENH/TST: add makedirs with mode fix, make_dir_tree

---

doc/source/index.rst

@klauer Like this?
This is not done, but if anyone has some feedback about whether this seems like a useful level of details I'd be glad to hear it before I press on.

DOC: Why not just use pyepics

---

ophyd/signal.py
ophyd/status.py
ophyd/utils/epics_pvs.py
tests/test_areadetector.py
tests/test_mca.py
tests/test_ophydobj.py
tests/test_quadem.py
tests/test_scaler.py
tests/test_signal.py

WIP - I (think) we only need this on signals

ENH: add tolerance, relative tolerance to signals (and set_and_wait)

---

doc/source/custom-devices.rst
doc/source/device-overview.rst

DOC: count time

---

ophyd/flyers.py
tests/test_flyers.py

Also fixes dtype='array' for non-pivoted option

ENH: allow monitorflyermixin to be pivoted on insert

---

.travis.yml

Added codecov to travis config.

BLD: try codecov

---

ophyd/signal.py
tests/test_quadem.py

Seeing some threading issues at SRX with the global cache from pyepics.
Completely untested, but a potential fix.

 FIX: pyepics threading tweaks for EpicsSignal

---

ophyd/signal.py
tests/test_device.py

Don't merge yet - still am not getting coverage

FIX: untested attributesignal attributeerror exception

---

ophyd/areadetector/cam.py
ophyd/areadetector/util.py

cc @gjwillms @imrealkaren @tacaswell

ENH: add pco edge camera definitions

---

ophyd/signal.py
tests/test_signal.py

REF: allow subscriptions through derived signals

---

ophyd/pseudopos.py
tests/test_pseudopos.py

Allows `setpoint` and `readback` to be read as normal `Device` `Components`
Closes #344

REF: pseudosingle is now a Device

---

ophyd/pseudopos.py

#358 rebased on master (with #353 now merged)

Enh pseudo lock

---

ophyd/areadetector/filestore_mixins.py

If users forget to put a trailing slash on the `*_path_template` for the filestore mixin, confusion ensures. This protects against that by automatically adding the trailing slash.
```
a/b/c -> a/b/c/
a/b/c/ -> a/b/c/
/ -> /
```

Ensure trailing slash

---

ophyd/signal.py
ophyd/utils/epics_pvs.py

FIX: allow set_and_wait to not have a timeout

---

ophyd/areadetector/filestore_mixins.py

- This falls back on the previous behavior if fs is not given.
- It warns that the fs arg will become required in the future.
Deploying at CMS reminded me that ophyd still requires filestore to be configured at import time via a file like `/etc/filestore.yml`. Once this is deployed and CMS's BL config correspondingly updated, it will not need a file at `/etc/filestore.yml` anymore.
Test coverage of this part of ophyd needs work, but this is how I checked that I got them all:
```
Daniels-MacBook-Air:ophyd dallan$ git grep "fs\."
ophyd/areadetector/filestore_mixins.py:        self._resource = self._fs.insert_resource(self.filestore_spec,
ophyd/areadetector/filestore_mixins.py:        self._resource = self._fs.insert_resource(self.filestore_spec,
ophyd/areadetector/filestore_mixins.py: …
```

ENH: Make FileStore instance used by AD fs mixins configurable.

---

ophyd/pseudopos.py

FIX/API: put readback first in pseudosingle

---

ophyd/utils/epics_pvs.py

I randomly remembered that we've been meaning to do this for months. Now back to vacation.

FIX: Impose upper limit on poll time back-off.

---

.travis.yml

As the helper scripts assume it

CI: build docs in conda env

---

ophyd/status.py
ophyd/tests/test_epicsmotor.py

Closes #419. ~~Needs tests.~~ Tested.

ENH: Add hooks useful for progress bars.

---

ophyd/quadem.py

I was losing to `getattr` at the time.

MNT: remove a debugging function

---

.travis.yml
doc/source/builtin-devices.rst
doc/source/device-overview.rst
ophyd/__init__.py
ophyd/epics_motor.py
ophyd/tests/test_epicsmotor.py

Enh motor bundle

---

ophyd/positioner.py
ophyd/pseudopos.py
ophyd/tests/test_pseudopos.py
ophyd/utils/epics_pvs.py

This is to support pseudo-positioner merging in bluesky.

Enh pseudopos extensions

---

ophyd/positioner.py
ophyd/pseudopos.py
ophyd/tests/test_pseudopos.py

It turns out even in python we are writing a vector library.
We may not need this...

ENH: teach PseudoPosition and RealPosition {+, -} and other useful lessons

---

ophyd/sim.py
ophyd/status.py
ophyd/tests/conftest.py
ophyd/tests/test_signal.py
ophyd/tests/test_utils.py

I sneaked in some style and warning changes as well.
closes #477

Fix fake PV

---

ophyd/device.py

pedant modification

---

ophyd/sim.py
ophyd/tests/test_sim.py

also fixed bug in poisson noise.

Random number with given seed

---

doc/Makefile
doc/source/api.rst
doc/source/architecture.rst
doc/source/area-detector.rst
doc/source/device-overview.rst
doc/source/status.rst

- Nicer URL (`_as_gen` -> `generated/`)
- Cleanup generated rst files as part of `make clean`

DOC: Use autosummary the same way we do in bluesky.

---

ophyd/ophydobj.py
ophyd/tests/test_ophydobj.py

Suggested by @stuartcampbell during an ophyd tutorial today

ENH: Add OphydObj.unsubscribe_all()

---

doc/source/docker.rst

Fixing issues found after merge of #495.

DOC: docker docs - correct typos and formatting.

---

doc/source/docker.rst

- Added missing links suggested by @jrmlhermitte in https://github.com/NSLS-II/ophyd/pull/484#issuecomment-345412853.
- Literal include of the docker scripts.

DOC: docker info update

---

.travis.yml
ophyd/utils/epics_pvs.py

An attempt with @tacaswell to better integrate caproto with ophyd.
Work in progress...

FIX: fixing caproto integration with ophyd

---

.travis.yml
requirements.txt

Don't merge. We will add strict dependence on networkx 2.0.
First, I have added `conda list` so we know what we're running on travis.

first test travis

---

.travis.yml
ophyd/_caproto_shim.py
ophyd/epics_motor.py
ophyd/pseudopos.py
ophyd/signal.py
ophyd/status.py
ophyd/tests/conftest.py
ophyd/tests/test_areadetector.py
ophyd/tests/test_device.py
ophyd/tests/test_epicsmotor.py
ophyd/tests/test_pseudopos.py
ophyd/tests/test_pvpositioner.py
ophyd/tests/test_signal.py
ophyd/tests/test_timeout.py
ophyd/tests/test_timestamps.py
ophyd/tests/test_utils.py
pytest.ini
test-requirements.txt

Changes to test suite to get it to (mostly) pass with caproto.

Fix caproto control layer

---

ophyd/quadem.py
ophyd/tests/test_quadem.py

ENH: Add sumAll to QuadEM

---

ophyd/ophydobj.py
ophyd/tests/test_device.py

WIP: From this issue [here](https://github.com/NSLS-II/bluesky/pull/1020).

ENH: Added labels to ophyd devices

---

ophyd/signal.py
ophyd/sim.py

This uses the new optional 'labels' feature in sim so that it is easier
to demo and document.

ENH: Add labels to devices in sim.

---

ophyd/quadem.py
ophyd/tests/test_quadem.py

I noticed this while writing release notes. Since it hasn't been in a release yet I think
we should fix the name.

API: Follow PEP8 naming (sumAll -> sum_all).

---

ophyd/device.py
ophyd/quadem.py
ophyd/tests/conftest.py
ophyd/tests/test_kind.py
ophyd/tests/test_quadem.py

Does not seem to be quite enough yet.

FIX: first pass at keeping lazy components lazy

---

doc/source/area-detector.rst

This has cost @prjemian a bunch of time.

DOC: add warning about inheritance order for top-level AD classes

---

doc/source/index.rst

Add all projects toctree to the ophyd documentation.
Motivated by https://github.com/NSLS-II/docs/issues/73.
Tested locally by building the documentation (required to do `sudo apt-get install graphviz`).

DOC: added all projects toctree to ophyd

---

MANIFEST.in

See https://github.com/NSLS-II/bluesky/pull/1042 for description of the problem.

BLD: include more files in distribution

---

ophyd/device.py
ophyd/signal.py
ophyd/tests/test_device.py

Immutable component names

---

ophyd/areadetector/base.py
ophyd/areadetector/cam.py
ophyd/areadetector/filestore_mixins.py
ophyd/areadetector/trigger_mixins.py

- add v33_cam_mixin to add `wait_for_plugins` component and configure
the stage sigs for parallel use
- add SingleTrigger33 which assumes that `wait_for_plugins` is
configured correctly
- mixin classes to bring a a few other 33 pvs

ENH: add classes for handling AD 33 IOCS

---

ophyd/areadetector/base.py
ophyd/areadetector/cam.py
ophyd/areadetector/filestore_mixins.py
ophyd/areadetector/trigger_mixins.py

Reverts NSLS-II/ophyd#600
See discussion an #602.  Moving to nslsii while we sort out naming schemes.

Revert "ENH: add classes for handling AD 33 IOCS"

---

ophyd/areadetector/plugins.py

This makes it harder to forget if it has been done or not.

MNT: use .plugins.register_plugin as a decorator

---

doc/source/area-detector.rst

I have added sections on creating custom AD device and plugin classes. This is based on my experience writing a new plugin class and reading through the docs/ code. There may be things I have wrong please check that it makes sense prior to merging.

Adplugin docs update

---

.travis.yml
doc/source/conf.py

~Do not merge. This is just a temporary PR to check whether ophyd's tests pass on Travis when run against caproto's ``fix-char`` branch. Once it passes, we'll merge that fix to caproto, tag a caproto release, and close this PR, unmerged.~
EDIT: The fixes to caproto have been merged into master, so I have removed the commits that aimed the ophyd CI at a caproto PR branch. During the time that the ophyd CI was failing, some unrelated issues cropped up. I will now merge the commits that fix them.

CI: Fix CI bit rot.

---

ophyd/sim.py
ophyd/tests/test_areadetector.py

Cherry-picked from 6d287ff276e38a21b4bfce62b506f7ea389b11bb to fix the tests

FIX/TST: fix some test issues in areadetector/sim

---

.travis.yml
install_epics_on_travis.sh
ophyd/tests/conftest.py
ophyd/tests/fake_motor_ioc.py
ophyd/tests/test_pvpositioner.py
test-requirements.txt

It's not as clean as it could be, but I think it's still better than the old docker solution.
TODO:
- Fake motor tests repeatably failing - I'd like to replace this with a simple caproto IOC that will be much easier to debug

CI: epics-on-travis, take 3

---

ophyd/sim.py
ophyd/tests/test_sim.py

add data_counter in datum and corresponding output numpy filenames. test to be added.

FIX: add data_counter when saving datum

---

ophyd/device.py
ophyd/ophydobj.py
ophyd/signal.py
ophyd/sim.py
ophyd/tests/test_device.py

From #618 - thanks @tacaswell for the useful feature

ENH: give easy access to the "dotted names" of signals and devices

---

ophyd/positioner.py
ophyd/sim.py
ophyd/tests/test_positioner.py

FIX: check limits on SoftPositioner

---

doc/source/builtin-devices.rst
doc/source/device-overview.rst
doc/source/signals.rst
ophyd/device.py
ophyd/epics_motor.py
ophyd/ophydobj.py

fixes #614 - should squash merge

DOC: Document hints, kind, and labels

---

ophyd/sim.py
ophyd/tests/conftest.py

This should help with pytest leakage (since python just puts the data anywhere)

pass path to sim so we can control where files are written

---

ophyd/device.py
ophyd/tests/test_device.py

FIX: None-ified components in Device subclasses

---

ophyd/areadetector/base.py

As discussed in NIKEA: https://nikea.slack.com/archives/C7PNB3BUG/p1551207337008300

BUG: Fix infinite recursion observed from reading shaped_image

---

.travis.yml

CI: remove prematurely added p4p control layer from travis matrix

---

.gitignore
ophyd/areadetector/plugins.py

Missed this one in the plugins PR. Notice any others?

MNT: Fix component names

---

ophyd/scaler.py

this line is superseded by the next line

MNT fixes #691

---

ophyd/areadetector/cam.py
ophyd/areadetector/detectors.py

Implemented with @mrakitin at NSLS-II RSOXS beamline.

Add GreatEyes detector

---

ophyd/device.py
ophyd/status.py

I noticed a couple of typos in some docstrings.
I also noticed that sometimes """ was used and sometimes ''' was used for docstrings in the same files.
It looked like """ was more prevalent in the files I was in, so I chose that, but if that is wrong then please ignore ;)

Couple of typos and some inconsistency in docstrings

---

ophyd/_caproto_shim.py
ophyd/_pyepics_shim.py
ophyd/device.py
ophyd/signal.py
ophyd/tests/conftest.py
ophyd/tests/test_areadetector.py
ophyd/tests/test_epicsmotor.py
ophyd/tests/test_pseudopos.py
ophyd/tests/test_signal.py
ophyd/tests/test_signalpositioner.py
ophyd/tests/test_utils.py
requirements.txt
test-requirements.txt

Builds on #710 
Closes #715 
TODO
------
* ~Remove temporary commits~
* ~Wait for pyepics version bump~
* ~Increase required version check in pyepics shim~

REF: pyepics shim

---

ophyd/epics_motor.py

Skip limits check in EpicsMotor.set_current_position()

fixes #726

---

ophyd/__init__.py
ophyd/device.py

- pass pv_telemetry through set_cl in 'auto' mode
- account for Python moving things around

MNT/FIX: two small fixes

---

ophyd/_dispatch.py

FIX: functools.partial has no __name__

---

ophyd/epics_motor.py

fixes #726 per https://github.com/bluesky/ophyd/issues/726#issuecomment-508772023

in set_current_limits, use force=True

---

.travis.yml
ophyd/signal.py
ophyd/tests/conftest.py
setup.py
test-requirements.txt

Pin caproto requirement to separate experimental dependencies.

---

.travis.yml
ophyd/_pyepics_shim.py
setup.py

remove deprecated kwarg "context"

---

.travis.yml
ophyd/_pyepics_shim.py
setup.py

Reverts bluesky/ophyd#774
I think this was accidentally merged. There were unaddressed suggestions from me. @tacaswell also had some non-blocking suggestions that I think are worth addressing, or at least making a little effort to address.

Revert "remove deprecated kwarg "context""

---

doc/source/architecture.rst
ophyd/status.py
ophyd/tests/test_status.py

TST: add a test to demonstrate MoveStatus._notify_watchers failure

---

README.md

This PR is to update the outdated information/links in the README.md file.

DOC: update outdated README

---

doc/source/release_notes.rst

Update release notes.

---

doc/source/debugging.rst
ophyd/ophydobj.py

Scope the OphydObj instance log messages.

---

ophyd/signal.py

Closes #848 
More details in issue

FIX: raise if ophyd.signal shadows standard library signal

---

doc/source/api.rst
doc/source/conf.py
doc/source/device-overview.rst
doc/source/index.rst
doc/source/release_notes.rst
doc/source/signals.rst
doc/source/status.rst
ophyd/areadetector/trigger_mixins.py
ophyd/status.py
ophyd/tests/test_epicsmotor.py

Includes first draft of release notes for the next release

Rewrite Status docs

---

doc/source/release_notes.rst

Started this branch before I realized #867 existed, but I've copied over the first point from there. The second point I think was for #866, but that got scrapped in favor of the upstream fix.

Release notes for version 1.5.1

---

ophyd/epics_motor.py

EpicsMotor: set hi limit to hi, lo to lo

---

.gitignore
ophyd/areadetector/cam.py
ophyd/areadetector/detectors.py
ophyd/areadetector/docs.py

Marking as WIP since I'm not 100% sure if I have added all the necessary code for this - first time working on `ophyd`. If someone could take a look and let me know if I missed anything I'd appreciate it.
This PR adds `Cam` and `Detector`classes for Emergent Vision Detectors, based on the `ADEmergentVision` driver I've written. The driver has recently been deployed on one of our beamlines and will need ophyd/bluesky support next.
AD Driver repo: https://github.com/jwlodek/ADEmergentVision
I also added `venv` and `.vscode` folders to the gitignore file

WIP - Adding classes for Emergent Vision Detectors

---

doc/source/release_notes.rst

* Bumped date to today
* Added note about Emergent Vision detector support, just merged this AM

Update 1.5.3 release notes.

---

ophyd/signal.py

Clarity how set_default_timeout interacts with inheritance.

---

.github/workflows/testing.yml

Run all tests, not just AD HDF5 tests.

---

ophyd/scaler.py

Found & solved this problem with the [APS USAXS instrument](https://github.com/APS-USAXS/ipython-usaxs/issues/426).

ensure ScalerCH .S has default auto_monitor=False

---

.github/workflows/publish-docs.yml

Fix copy/paste typo in workflow condition.

---

ophyd/areadetector/cam.py
ophyd/areadetector/detectors.py

This PR adds classes for the xspress3 using areaDetector version 3+.

add Xspress3Detector and Xspress3DetectorCam

---

docs/source/architecture.rst
ophyd/sim.py

Migrated from a slack conversation.

Doc multi collect flyer

---

pytest.ini
requirements-test.txt

CI: add pytest-rerunfailures for flaky marker and fix deprecation warning

---

ophyd/positioner.py

Motivated by https://github.com/bluesky/hklpy/issues/147

DOC Describe init_pos kwarg

---

ophyd/device.py

cast config_attrs as list(config_attrs)

---

ophyd/areadetector/plugins.py

xml_file_name must be a string

---

.github/workflows/testing.yml
ophyd/_dispatch.py
ophyd/_pyepics_shim.py
ophyd/ophydobj.py
requirements.txt

This accounts for a change in behavior of IntFlag in py311.

Fix enum py311

---

ophyd/areadetector/cam.py
ophyd/areadetector/detectors.py

- close #1054
https://github.com/areaDetector/pvaDriver

add support for EPICS area detector pvaDriver cam

---

docs/user_v1/reference/positioners.rst
ophyd/pv_positioner.py

It's more fussy since v2 changes merged in...

Fix docs linking

---

README.rst

Also fixed some minor spelling issues.

DOC: fix install instructions in README

---

ophyd/v2/_channelsim.py
ophyd/v2/tests/test_epicsdemo.py

Channel sim can now initialise simulated values for python Enum data types.

BUG: Let channelsim work with enums

---

ophyd/v2/_channelca.py
ophyd/v2/tests/test_ca.py

ENH: Add enum descriptor support to ChannelCa

---

ophyd/v2/core.py
ophyd/v2/epicsdemo/__init__.py
ophyd/v2/tests/test_epicsdemo.py

This fixes the linting issues on master, and improves the StandardReadable interface

v2: Make stage/unstage async

---

ophyd/v2/core.py
ophyd/v2/tests/test_core.py
ophyd/v2/tests/test_epicsdemo.py

solves https://github.com/bluesky/ophyd/issues/1117

Let SimSignalBackend accept npt.NDArray datatypes

---

ophyd/areadetector/filestore_mixins.py
ophyd/tests/test_areadetector.py

Fixes #1146 
`FileStoreBase` "validates" its write path template (unless a read path template is also supplied). In this context that means it checks if the store's root is an ancestor of the template, but does not allow `.` as the write path.
The use case for this is making a file store write to its own root. 
Changes in this PR to address this:
* Make `FileStoreBase` consider the value of root (or simply `.`) a valid write path under root.
* Refactor common behaviour out of read and write path properties
* Add suite of tests to validate that read and write paths are processed properly in a variety of use cases
* Check that behaviour holds whether root/write/read paths are passed in the constructor or set after object creation
* Add a minimal dummy implementation that is used in the …

Allow write path template on FileStoreBase to include .

---

ophyd/status.py
ophyd/tests/test_status.py

Fixes #1244 
To test:
* Confirm new test passes

Do not stop devices that cannot be stopped on Status failure
