bluesky/ophyd

ophyd/runengine/runengine.py

Not sure if this was intended or not, but if no positioners are provided then the run loops infinitely until Ctrl-C. This change only loops through once if the positioners are not set (None) or they are a null list. 
This is just a suggestion, but has the added advantage that a "count" as per spec just becomes a run() of the base scan class and all data is saved as if it was a scan. I like this as it is a good way to trigger a single image acquisition for example.
P.S. Also formatted as per PEP8

ENH: run only loops once if no positioners are provided

---

ophyd/userapi/scan_api.py

If the user does not pass a `settle_time` kwarg use the
settle time on the scan object, not 0.

BUG : respect object settle time if not specified

---

ophyd/controls/area_detector.py

Some overly aggressive changes by yours truly during the XPD deployment broke CSX. Those changes are here reverted. CSX detectors work now. I will need to verify that XPD works before this is merged / released.
In a separate commit, Stuart cleaned up and simplified his stats code.
As an incidental result of these changes, the error-level log messages issued by ophydobj.py have been resolved.

Fix AD errors

---

ophyd/controls/area_detector.py

* Acquisition mode should have been multiple. This was a bug.
* To be safe, ophyd enables the TIFF plugin on configure and disables on deconfigure.
* AutoSave must be on.

FIX: TIFF should use multiple mode.

---

ophyd/runengine/runengine.py

`positioners` was in `kwargs`, which is passed to `_move_positioners` directly. Removing it caused `positioners` to be `None` in `_move_positioners`.
(ref 4fbbecf6f3b991787dbd0bb7aa87abdd922c7f09)

BUG: scans using positioners failed

---

ophyd/controls/positioner.py
ophyd/controls/pseudopos.py
ophyd/controls/scaler.py
ophyd/controls/signal.py
ophyd/session/sessionmgr.py
ophyd/utils/epics_pvs.py
ophyd/utils/errors.py

Addresses #136 and #90
Basically, avoids the assumption in a couple of `__init__`-ializers that a connection to the controls layer has been made.
This means reads/writes to disconnected channels will `raise`, and loading of startup configuration files will not stall if channels cannot be reached initially. Need to have a think about how best to inform users that only M out of N of their devices made a connection by the time the __In [1]:__ prompt lands. Suggestions welcome.
NOTE: this does _not_ include more graceful handling of swarms of (dis)connects.

[FIX] CA (dis)connection management

---

ophyd/controls/areadetector/detectors.py

Simple enhancement I've been using at the HXN - allow ADSignal descriptor PV names to be filled in with information from the detector/plugin object. Useful for devices with not-so-consistent PV prefixes/suffixes:
```python
class EpicsROI(ADBase):
'''A configurable Xspress3 EPICS ROI'''
bin_low = ADSignal('C{self.channel}_MCA_ROI{self.roi_num}_LLM')
bin_high = ADSignal('C{self.channel}_MCA_ROI{self.roi_num}_HLM')
enabled = ADSignal('C{self.channel}_ROI{self.roi_num}:EnableCallbacks',
has_rbv=True)
```

ENH: Allow dynamic PV names in ADSignals

---

ophyd/controls/area_detector.py
ophyd/controls/detector.py
ophyd/controls/ophydobj.py
ophyd/controls/scaler.py

The signature changes are noncontroversial. Someone read them to make sure I didn't miss something?
I called the new property 'state'. I am not attached to that name.@klauer expressed some minor reservations about 'report' because it could be a verb or a noun -- hard to guess if it's a method or a property.
Whatever we choose let's get this merged soon so the framework is in place and tested in time for beam. We can add actual *content* to state pretty safely as we go.

Fix signatures of configure/deconfigure; add 'state' property.

---

ophyd/callbacks.py

See [https://github.com/NSLS-II/bluesky/issues/220] for details
Made a bit more generic from my HXN implementation as `EpicsSignal` shouldn't be necessary. Added in some EPICS database notes.

ENH: add top-level bluesky-related callbacks module (with uid publisher)

---

ophyd/utils/epics_pvs.py

Not sure how this got buried. This is a fix from @tacaswell, but is really important for ophyd as with the current installation we're getting all local timestamps (i.e., when the monitor update was received).
Alternatively we should just not set 'form' manually anymore. After a lengthy discussion (and some of my fixes) with pyepics-lead @newville, he changed the default to using server-side PV timestamps.

FIX: interpret badly-formed version from pyepics

---

.mailmap

The commit history of this project is littered with various names for a
number of people (I am the worst offender here!)  The mailmap blames the
correct people for the commits that were made. Again, this is mostly so
that I can be blamed for the commits that are my fault :)

MNT: Add a .mailmap

---

ophyd/areadetector/filestore_mixins.py
ophyd/areadetector/plugins.py

This uses Stream mode, which allows us to write one HDF5 file per *run* (strictly speaking, per stage/unstage), not per acquisition.
I executed [this script](https://gist.github.com/danielballan/42e854fdb5e65f2cb809), accessing a SimDetector IOC running AD 2.2 at xf23id (actual 2.2, not the customized branch run in production at CSX).

ENH: Successful test on HDF5 SimDetector with AD 2.2

---

ophyd/device.py

Here, I use `self._original_vals` to keep track of which signals have actually been set in the midst of an ongoing stage. During unstage,  the values are removed. We discussed earlier (nodding to @klauer) that keeping the stash might be useful, but I think this mode of operation is actually the most useful for debugging.
And now, `self._staged` is merely a check on the non-emptiness of `self._original_vals`.
I discovered the problem and tested this solution using the following. As with so much else, an automated test should be made once the deployment is done.
```python
pe1.stage()  # raised IOError -- directory didn't exist
pe1._staged   # should be False
pe1.tiff._staged  # should also be False
pe1.stage()  # should be allowed, and again raise an IOError, not a RuntimError about already …
```

Recover from a failed stage

---

.travis.yml
ophyd/device.py

If `self.trigger_signals` is an empty list, assume there is no need to
trigger the device (and it is immediatly done) instead of raising.
My proposal for NSLS-II/bluesky#279

MNT: if no trigger signal, assume no need

---

ophyd/__init__.py
ophyd/device.py
tests/test_ophyddevice.py

Adds a Component which takes a dynamic format string, useful for when PV names need to be dynamically generated.
This differs from Component in that the parent prefix is not automatically added onto the Component suffix. Additionally, `str.format()` style strings are accepted, allowing access to Device instance attributes:
```python
>>> from ophyd import (Component as C, FormattedComponent as FC)
>>> class MyDevice(Device):
...     # A normal component, where 'suffix' is added to prefix verbatim
...     cpt = C(EpicsSignal, 'suffix')
...     # A formatted component, where 'self' refers to the Device instance
...     ch = FC(EpicsSignal, '{self.prefix}{self._ch_name}')
...
...     def __init__(self, prefix, ch_name=None, **kwargs):
...         self._ch_name = ch_name
... …
```

ENH: add FormattedComponent

---

ophyd/areadetector/filestore_mixins.py
ophyd/areadetector/plugins.py
ophyd/areadetector/trigger_mixins.py

* Allow PluginBase to be used outside of Detectors (as can be necessary or desirable) - this comes in the form of just checking to see if parent has a 'cam' attr
* PEP8 cleanups on filestore/trigger_mixins
* Missing import on trigger_mixins shows our tests and coverage are lacking

FIX: plugin stage

---

ophyd/device.py
tests/test_device.py

During an offline discussion, we found that if a component is listed in the configuration_attrs list, we want both its metadata and its values.
For example, if component 'a' is in a device's read_configuration list, calling device.describe_configuration() will return an aggregate of both device.a.describe_configuration() and device.a.describe().

FIX: make Device.configuration_attrs include data

---

circle.yml
ophyd/areadetector/base.py
ophyd/signal.py
tests/coverage_full.sh
tests/test_signal.py

Should be a backward-compatible refactor
* Both EpicsSignal and EpicsSignalRO inherit from EpicsSignalBase. Some leftovers from Signal still being read-write, but I think it's an improvement. 97% coverage with tests (only trigger is untested)
* Additionally, odd ReadOnlyError bug should be fixed (thanks, @tacaswell). PVs cached and already connected on the pyepics level were calling callback functions prior to the EpicsSignal even getting their instance.

EpicsSignalRO refactor

---

ophyd/utils/epics_pvs.py

This causes about 3 extra times through the loop and could provide 10x
speed up.

MNT: reduce the default poll time on set_and_wait

---

ophyd/device.py
ophyd/utils/errors.py
tests/test_device.py

stop is called on all Devices in the hierarchy. Calls to sub-class stop() are error-tolerant such as to not cause the top-level stop() call to die prematurely.
ExceptionBundle contains all of the exceptions that were caught during a stop() call.
Example Exception message for the test:
```
ExceptionBundle: 2 exception(s) were raised during stop:
sub2.subsub raised Exception('stop failed for some reason',)
sub3.subsub raised Exception('stop failed for some reason',)
```

ENH: flesh out Device.stop

---

.travis.yml

Also, cause Travis to fail sooner if it can't find libca (for some reason)

BLD: dump pyepics version to stdout on Travis blds

---

ophyd/commands.py

This device does not get collected by `get_all_positioners`:
```python
class XYMotor(Device):
x = Cpt(EpicsMotor, ...)
y = Cpt(EpicsMotor, ...)
Should we add a `set` method and use duck-typing to identify positioners? See attached function.

ENH: Add duck-typing namespace scraper.

---

ophyd/commands.py

`wh_pos()` died when it tries to call `_signals` on a PseudoSingle. We should only be recursing through Devices, not Positioners.
All of this will go away later -- just trying to make something reasonably clean that works for this cycle.

FIX: more careful recursion that works on PseudoSingle

---

ophyd/epics_motor.py
ophyd/signal.py
tests/test_signal.py

Replaces #248 
Should fix #246 
Tests passing locally, but we should make extra sure the logic is correct for re-initialization of `epics.PV`s

FIX: re-initialize automonitor when an EpicsSignal subscription is made

---

ophyd/areadetector/trigger_mixins.py

In `SingleTrigger`, we expose the `_acquisition_signal` (which is by default `self.cam.acquire`). But then we subscribe to `self.cam.acquire` before the subclass has the opportunity to assign a different signal to that role. I noticed @dchabot working around this like so:
```python
class FastTrigger(SingleTrigger):
def __init__(*args, **kwargs):
...
self._acquisition_signal.clear_sub(self._acquire_changed)
```
I have had to work around the same problem myself at CSX and XPD. This PR allows subclasses to alter `_acquisition_signal` *before* subscriptions are hooked up. Also, it removes the subscriptions upon unstaging, which I probably should have done in the first place. Agree, @dchabot?

MNT: Make acq signal customizable in SignalTrigger subclass.

---

ophyd/areadetector/filestore_mixins.py
ophyd/areadetector/trigger_mixins.py
ophyd/device.py

- debug messages giving old and new values of stage_sigs as they are set
- one more subtlety with stage/unstage logic: a device should not be marked `_staged = False` until unstaging has successfully finished so that you can't stage until everything is unstaged

More stage debug

---

.travis.yml
circle.yml
conda-recipe/meta.yaml

six is no longer a dep of ophyd.
Before this PR
```
$ git grep six
.travis.yml:  - conda install numpy pyepics prettytable filestore six ipython pyolog
circle.yml:    - conda install numpy pyepics prettytable filestore six ipython pyolog
conda-recipe/meta.yaml:    - six
```

MNT: Remove six as a dependency

---

ophyd/pseudopos.py

Someone's using PseudoPositioners... yes!
These are two simple bugs that should never have gotten to users. I suppose it's my fault for not having finished the PseudoPositioner tests post-refactor (and git-blame would confirm that). 
Things seem to be working well enough with this PR though.

FIX: pseudo move_single and pseudosingle limits

---

ophyd/areadetector/filestore_mixins.py

Need to be able to:
1. Modify the filenames being saved through FileStoreBase (NFS+PIMS choke with hundreds of thousands of files in one directory)
2. Create the directory and set permissions
With this small change, I can do both in my subclass. For (1) I'm making a subdirectory with the start of the filename uid since I don't have access to any scan information during `stage()`.
P.S. @danielballan here's an opportunity to disagree!

MNT: hook for filestore mixin make_filename

---

ophyd/device.py

I think this will give us the information we need to address https://github.com/NSLS-II/bluesky/issues/343. Without a reproducible bug report it's hard to be sure, but either way this is useful. Now a plan can know what children have been staged to avoid staging a parent and then redundantly trying to stage its child.

ENH/API: stage and unstage report objects they touched

---

ophyd/epics_motor.py

Reasons:
* Backward compatibility with routines developed when motors only returned one value
* The vast majority of the time, people want the user_readback, and if they need to check the user_setpoint of course they can still access it.
We talked about doing this in #170 but it seemed like a small detail at the time. Don't worry: this is is not the first wave in a deluge of naming-related PRs into ophyd Device attribute names. EpicsMotor is the only place where I would advocate for overriding the verbose (if nicely explicit) default. Just as users like the special `position` and `value` attributes, they want their `eta` data to show up as "eta," not "eta_user_readback." We might as well make this a facility-wide standard; we are already writing this into most of the beamline configs by …

API: Change default name of user_readback.

---

ophyd/mca.py
tests/test_mca.py

* Split mca record class into just the EPICS mca record and the other one with additional Start and EraseStart records (@dchabot thoughts about naming this better, or if those separate records belong on the subclassed `Device`s instead?)
* Can't have namedtuple keys with leading underscores - as such, no components with leading underscores ( :( )
Use case is the (mca-mode) Struck SIS3820 scaler, used on the vast majority of beamlines: (config ref [struck_scaler.py](https://github.com/klauer/hxntools/blob/84c8f2831b23475e229d206ba16b49eebc3b31d6/hxntools/struck_scaler.py))

FIX: minor mca tweaks

---

ophyd/epics_motor.py
ophyd/positioner.py
ophyd/pseudopos.py
ophyd/pv_positioner.py
ophyd/status.py
tests/test_positioner.py
tests/test_pseudopos.py
tests/test_pvpositioner.py

Proposed fix for #279
`settle_time` is added at the lowest level possible, making it possible to use throughout the hierarchy.
I think this is the cleanest it can possibly be done. Commence the bikeshedding.
If we can agree this isn't a terrible idea, I'll add it to `Device` as a kwarg as well.

ENH: Settle time for all positioners, and more

---

ophyd/epics_motor.py
ophyd/positioner.py
ophyd/pseudopos.py
ophyd/pv_positioner.py
ophyd/status.py
tests/test_epicsmotor.py
tests/test_positioner.py
tests/test_pseudopos.py
tests/test_pvpositioner.py

This is #297 (due to @klauer) plus one small commit that gives `move` no timeout by default. Other timeouts in the codebase (like `wait_for_connection`) are left as is.

Default timeout

---

ophyd/__init__.py
ophyd/signal.py
tests/test_signal.py

The concept of a 'derived signal' with a value and description based on another.
Submitting to see what people think - not saying this has to go in or necessarily even should. 
As an example, I've used this in an ROI's low and high eV `Component`s, which calculate user-friendly eV units from bin numbers.:
```python
class EvSignal(DerivedSignal):
'''A signal that converts a bin number into electron volts'''
def __init__(self, parent_attr, *, parent=None, **kwargs):
bin_signal = getattr(parent, parent_attr)
super().__init__(derived_from=bin_signal, parent=parent, **kwargs)
def get(self, **kwargs):
bin_ = super().get(**kwargs)
return bin_to_ev(bin_)
def put(self, ev_value, **kwargs):
bin_value = ev_to_bin(ev_value)
return super().put(bin_value, **kwargs)
def describe(self):
desc = …
```

ENH: Derived signal

---

ophyd/device.py
ophyd/epics_motor.py
ophyd/mca.py
ophyd/pseudopos.py
ophyd/pv_positioner.py
ophyd/scaler.py
tests/test_device.py
tests/test_scaler.py

As discussed. Is it safe to say that no beamline configs are using it?

REF: remove Device.monitor_attrs

---

ophyd/__init__.py

I assume I will be voted down here, but what about *calling* `setup_ophyd()` in the `__init__.py` as well? We have previously seen cases where executing code on import is a tempted but bad idea (bluesky's qt_kicker) but I'm not convinced this is in the same category. Is there ever a case where it *shouldn't* be called? Should ophyd be in charge of setting itself up?
Note: as stated in the title, this PR does not do what I am suggesting above; it merely imports it in a more obvious place. I assume that is non-controversial.

MNT: Import setup_ophyd at top level.

---

ophyd/commands.py

Positioners as sub-devices get ordered randomly without this in `wh_pos`

MNT: scraped positioners sorted by name

---

ophyd/areadetector/cam.py

Supersedes #303; Adds: linux firewire, lightfield, pixirad, point grey cameras
Note: I do not have the detectors to check this.
Generated with `ophyd.areadetector.utils.create_detector_stub()` and tweaked by hand.
@gjwillms some of your components were in `CamBase`, and I tried to tweak some names to keep backward compatibility with yours. There may be some others I didn't catch. If you have name suggestions (complaints) now's probably the time to fix this up...

ENH: flesh out remaining areadetector.cams

---

ophyd/signal.py
tests/test_signal.py

per conversation with @klauer, `Signal.set` is a synonym for `Signal.put`, so that things like `det.count_time.set(2)` work as expected.

ENH/TST: Implement Signal.set()

---

ophyd/signal.py
ophyd/status.py
tests/test_flyers.py
tests/test_signal.py

This will give us the option to use `set` similar to `Positioner`s for all signals, with asynchronous status completion objects.
* `Signal.set` uses `set_and_wait` (runs in a separate CAThread) - and so all signals derived from this will do the same
* `EpicsSignal.set` uses put completion if specified by the user (requires no background thread), and falls back to `set_and_wait`
* Switched Signal from using `StatusBase` -> `Status`

ENH: fully fleshed out Signal.set and EpicsSignal.set

---

ophyd/utils/startup.py

No crashing at exit with Python 3 and pyepics/pyepics@e4cd21cfaf63bc2150d5679ad4f6cf75deb2ff0f
We should make sure that this new version of pyepics (and of course ophyd) gets deployed for the next cycle.

FIX: cache clearing unnecessary with new pyepics

---

ophyd/device.py
ophyd/flyers.py
ophyd/utils/__init__.py
tests/test_flyers.py

* `describe_collect()` is separate from the normal `Device.describe()` in that it has a description of what `collect()` will return. The return value is also a list of descriptions, whereas `describe` and `describe_configuration` return only a single dictionary each.
* `complete()` returns a status object indicating when data is ready for collection (all implemented flyers return completed status objects currently)
* `pause` pauses flyer data acquisition
* `resume` resumes after a pause

API/TST: flyers have methods: complete, describe_collect, pause, resume

---

ophyd/areadetector/filestore_mixins.py

Makes it easy to support other specs like 'AD_HDF5_SWMR'.
Now, to handle SWMR specifically it might be better to set up ophyd's HDF5FilePlugin to ask AreaDetector's HDF5 plugin whether it supports SWMR, but that's a bigger project.
This simple knobs seems like a useful addition in any case.
attn @stuwilkins

ENH: Make filestore spec configurable through attribute.

---

.travis.yml
ophyd/areadetector/base.py
ophyd/areadetector/plugins.py
ophyd/quadem.py
tests/test_areadetector.py
tests/test_quadem.py

- find all plugins that ophyd knows about
- find a plugin by port name
- validate that the full processing path is know to ophyd
- turn blocking_callbacks on by default in all Plugin stage methods

ENH: add methods to walk AD plugins

---

ophyd/mixins.py
tests/test_positioner.py
tests/test_signalpositioner.py

Alternative to PVPositioner modification idea (#331); ~~only for discussion~~
Could be used as follows:
```python
sig = EpicsSignalPositioner('Prefix:Motor.RBV', write_pv='Prefix:Motor.VAL', tolerance=0.005)
sig.move(5.0)
```
This would use `set` -> `set_and_wait` for moves on a signal, which boils down to `abs(readback - setpoint) <= tolerance` (ignoring the unset relative tolerance), so once at 4.995 <= position <= 5.005 would run the done move callbacks, etc.

ENH: add signal/positioner mixin

---

ophyd/areadetector/plugins.py

Looks like a copy/paste error from ages ago

FIX: Size-link does not exist on the ROI plugin

---

ophyd/__init__.py
ophyd/quadem.py
tests/test_quadem.py

for each type of device (NSLS_EM, TetrAMM, APS_EM, etc).

FIX: For QuadEM the port_name must be different

---

ophyd/signal.py
ophyd/utils/epics_pvs.py
tests/test_utils.py

Avoid typos where a PV.FIELD is passed into a Device which represents
an record (and hence is going to use that pvname as a base to find other
fields).
attn @hhslepicka

MNT: validate there is at most 1 '.' in pvname

---

ophyd/device.py

Speaking of lazy instantiation, devices with `stage_sigs` typically break lazy instantiation by including references to signals in the `__init__`, such as:
```python
class AD(AreaDetector):
def __init__(self, ...):
super().__init__(...)
self.stage_sigs[self.cam.whatever] = 5
```
This PR allows the keys in stage sigs to be strings, like so:
```python
class AD(AreaDetector):
def __init__(self, ...):
super().__init__(...)
self.stage_sigs['cam.whatever'] = 5
```
Here, the attribute lookup / signal connection happens during `stage()` instead of during `__init__`. This should significantly speedup reload times for IPython profile scripts that include many area detectors.
The old usage is still allowed. In cases where the key refers to something that is not an attribute of `self`, it will still …

ENH: Allow stage_sigs keys to be attr names, not attrs.

---

ophyd/epics_motor.py

Add `.DIR` channel and organize existing signal into groups
Related to #369

ENH: add user_offset_dir to EpicsMotor

---

ophyd/ophydobj.py
tests/test_ophydobj.py

If a subscription is added or removed while iterating over the list of
callbacks to run, odd things (like skipping running callbacks) may
happen.  To prevent this keep a local (shallow) copy of the callbacks to
iterate over.
attn @gjwillms

FIX: protect against mutating subs list while iterating

---

ophyd/areadetector/filestore_mixins.py
ophyd/areadetector/plugins.py
ophyd/areadetector/trigger_mixins.py
ophyd/mca.py
ophyd/quadem.py
ophyd/scaler.py
tests/test_quadem.py

In #351, we added the option to specify stage_sigs as attribute *names* as opposed to attributes. This restores the intended lazy-connecting feature of ophyd objects, where they don't need to connect to all their signals at __init__ time.
This PR takes advantage of that in more places in the codebase. It should improve the startup time of IPython at SIX and others.

REF: Make use of #351 to make more devices lazy.

---

.travis.yml
install_epics_on_travis.sh
requirements.txt
setup.py
test-requirements.txt

* Add tests on 3.6; drop tests on 3.4 (superceding #386)
* Add a test using pip install and EPICS from Debian (no conda).
* Use requirements.txt and test-requirements.txt.
This applies the same Travis cleanup @tacaswell and I applied to bluesky in https://github.com/NSLS-II/bluesky/pull/660 and https://github.com/NSLS-II/bluesky/pull/668

BLD/CI: List requirements descriptively; test pip-based build.

---

doc/source/area-detector.rst
ophyd/areadetector/filestore_mixins.py

This is used as part of the device API, replaced it with a path on
the filestore plugins

FIX: show-stopper bug of shadowing root

---

ophyd/areadetector/plugins.py
tests/test_quadem.py

This avoid issues when the String representation was changed on the NDPluginBase.template file at areaDetector. The int value never changes.
The current implementation works fine but this change makes it stronger to survive in those cases as mentioned above.
Here at SLAC we faced that and the merge of this PR would avoid the annoyance of creating a class that inherits from PluginBase just to redefine stage.
Att. @teddyrendahl

MNT: Use the int value at EnableCallbacks instead of the string value

---

ophyd/areadetector/base.py

This allows one to change for instance the nd_array_port in a plugin and have a correct validation on the asyn ports.
Here is the use case for that...
At the normal operation the camera is pointing to a stream of data that is limited in terms of data rate and sometimes with binning
when we want to collect data we want to switch the plugin nd_array_port to the CAM stream which is the raw data coming as fast as the camera can acquire.
Attn @danielballan @tacaswell

FIX: ADBase stage should only validate_asyn_ports after staging the signals

---

ophyd/status.py

What seems to be happening is that computing the fancy string
representation was taking too long and the motor was finishing it's
move.  Or something.

FIX: unbreak the homing tests

---

ophyd/areadetector/trigger_mixins.py
ophyd/quadem.py

This is a fun one. Bluesky can now show a progress bar indicating
how many images out of the total `num_images` have been acquired.
Tested in the wild on CSX's fast CCD. Existing tests should cover it.
Closes #427

ENH: Add special status objects for AD triggering progress bars.

---

ophyd/areadetector/detectors.py
ophyd/areadetector/plugins.py
ophyd/tests/test_epicsmotor.py
ophyd/tests/test_quadem.py

Recall https://github.com/NSLS-II/ophyd/issues/245
I believe this is a non-breaking change --- it just adds a knob -- but I am not 100% confident that the change to `detectors.py` is correct because I am not sure what `self.enable.get()` returns.

ENH: Make automatic plugin-enabling on stage() optional.

---

requirements.txt
test-requirements.txt

- databroker is optional and available on PyPI
- pyOlog is no longer used in tests
- tifffile, pims, h5py will come in through test dependency on databroker

BLD: Update requirements.

---

ophyd/utils/epics_pvs.py

Small change. This is actually the only location in ophyd outside of tests and examples with a call to logger.info. The info level is often used for on-screen prints, and this one was spamming me today during `stage()` and `unstage()`, so I'd like to request that it be moved to debug. I don't think a user wants a print out every time we check that the put wait has finished, as this may produce log messages every 0.1s.

ENH: Switch the wait log message in set_and_wait from info level to debug level

---

doc/Makefile

There seems to be an issue with sphinx's parallelization feature
that is not specific to our projects. This PR removes the `-j` option
to get things working again until it is resolved.

CI: Turn off parallel building for now because it is broken.

---

ophyd/status.py
ophyd/tests/test_status.py

Created a `SubscriptionStatus` object that uses the built-in Ophyd event system to update itself
The `SubscriptionStatus` is a subclass of the `DeviceStatus` object that accepts a device, event_type and callback. The callback is registered at initialization and automatically cleared from the device after the status finishes via completion or timeout.
While `PositionerBase` handles any device that has a `DMOV` type flag to subscribe to, I found myself rewriting a lot of code for simpler devices that did not have this flag. For instance if you wanted to set signal A, and wait for signal B and C to reach specific values you were stuck implementing this on a class by class basis. Now you can just write a simple function to check the state of these PVs and summarize it in a boolean, then plug …

ENH: SubscriptionStatus

---

ophyd/positioner.py
ophyd/status.py
ophyd/tests/test_status.py

I'm reviving this very old branch because I keep seeing places
where it seems useful to me, including most recently a use case
that @swilkins found.
Unlike my first attempt, this one is fully backward-compatible.

ENH/API: Make status objects support __and__

---

.travis.yml
doc/source/device-overview.rst
doc/source/release_notes.rst
ophyd/device.py
ophyd/scaler.py
ophyd/tests/test_areadetector.py
ophyd/tests/test_device.py
run_tests.py

API: Deprecate signal_names; rename it to component_names.

---

ophyd/device.py

This makes the pure-synthetic case simpler.
close #408

MNT: set default prefix in Device init

---

ophyd/device.py
ophyd/tests/test_areadetector.py
ophyd/tests/test_device.py
ophyd/tests/test_flyers.py
ophyd/tests/test_mca.py
ophyd/tests/test_scaler.py
ophyd/tests/test_status.py
ophyd/tests/test_timestamps.py

This ensures that the names that appear in the read dictionary are
always human-readable.
In practice if this is left out it is accidental and results in saved
data with keys that are a concatenation of the PV prefix with the
names of the children in the python class.  This is neither human
understandable nor a valid / existing PV.  Neither humans nor machines
can read this.
Keeping keyword only to preserve the ability to have sub-classes with
more than one required positional arguments.
Do not want to make it the first positional argument to avoid massive
API breakage and the convention of 'last positional argument' is
brittle.
A keyword-only argument also clearly disambiguates the name (for
humans) from the prefix (for hardware).

API: make the name keyword to device a required keyword only arg

---

ophyd/device.py
ophyd/tests/test_device.py

The new verbose summary, currently available as ``print(device)``, is great to
have but overwhelmingly verbose when it shows up inside a log or a Traceback.
This PR moves that verbose summary into a new method and restores the old behavior
of ``__str__`` so that ``print(device)`` does the same thing as ``repr(device)``.
Notice that ``summary()`` prints but returns ``None`` so that the line breaks
are correctly displayed. The string itself is available programmatically from
``_summary()``.
Example:
```python
In [1]: from ophyd.sim import motor
In [2]: motor
Out[2]: SynAxis(prefix='', name='motor', read_attrs=['readback', 'setpoint'], configuration_attrs=[])
In [3]: print(motor)
SynAxis(prefix='', name='motor', read_attrs=['readback', 'setpoint'], configuration_attrs=[])
In [4]: …
```

MNT: Move verbose summary from __str__ into new method, 'summary'.

---

ophyd/sim.py

Small change. I noticed that `SynSignal` gave tracebacks like the following if `func` wasn't provided. The docs claim this should be optional, so the simple fix is to initialize a value for the `._readback` attribute.
```
In [1]: from ophyd.sim import SynSignal
In [2]: sig = SynSignal(name='test')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-8e56780657fc> in <module>()
----> 1 sig = SynSignal(name='test')
~/conda/envs/nikea/lib/python3.6/site-packages/ophyd/sim.py in __init__(self, func, name, exposure_time, precision, parent, loop)
82         self.precision = 3
83         self.loop = loop
---> 84         super().__init__(value=self._func(), timestamp=ttime.time(), …
```

FIX: Initialize SynSignal with a None value if no func provided.

---

ophyd/sim.py

This makes BestEffortCallback work until LiveTable can be fixed.

API: Add empty hints for SynSignalWithRegistry.

---

ophyd/areadetector/plugins.py
ophyd/device.py

As pointed by @jrmlhermitte in an internal document, settting
```py
cam05.stats1.read_attrs = ['centroid']
```
does not have any effect on what is read because
```py
cam05.stats1.centroid.read_attrs == []
```
I think all plugin subdevices should include all attrs as read_attrs
by default. The effective default behavior will not change because
```py
cam05.stats1.read_attrs == []
```
but if ``'centroid'`` is added, its x and y components should come
along for the ride.
- Extend DynamicDeviceComponent to accept optional default_read_attrs and
default_configuration_attrs arguments, which is will assign as class
attributes on the class it dynamically creates.
- Systematically add default_read_attrs=(...) to every DDC on every plugin.

For all plugin sub-devices, include all attrs in default_read_attrs.

---

ophyd/status.py

Ran into a use case in deployment where we did not want to run the callback immediately and instead wait for the first monitor callback from a signal. This PR adds the `run` keyword to the `SubscriptionStatus` to pass directly into the `.subscribe` method of the Ophyd object. Default was left as `True` so behavior will remain the same.

ENH: Add keyword to not run SubscriptionStatus immediately

---

ophyd/utils/epics_pvs.py

`set_and_wait` currently accesses `signal.tolerance` on the first line. This is a problem because the `tolerance` property is wrapped with a `raise_if_disconnected` decorator, which prevents the whole method from being run if the `EpicsSignal` object has not finished connecting.
This happened to me with the `AreaDetectorComponent` objects. Since these are the only `Component` objects that are set as `lazy=True`, there was no guarantee that the connection finished in time for my `set_and_wait` call.
I expect that these `epics_pvs` utils should work even if the connection hasn't finished yet, so here I've reordered the method so that the `put` and `get` calls happen first, which call `wait_for_connection` on the `_write_pv` and `_read_pv` attributes respectively. This guarantees that the …

FIX: Reorder set_and_wait to avoid race condition

---

ophyd/device.py
ophyd/tests/test_device.py

Currently, if you have a signal that begins with an underscore it is renamed in the `_device_tuple` object to be something completely unhelpful like `_1` . This will go unnoticed until you call `.get()` on your device and we try and stuff `component_names` into the tuple. This raises an Exception that looks as follows:
```
__new__() got an unexpected keyword argument '_your_signal'
```
This may lead a dull programmer to blame his compatriot for mangling a class's MRO
https://github.com/pcdshub/pcdsdevices/issues/157. 
Anyways I looked through some documentation, but I found nothing saying that you can't start a component name with an underscore. This PR makes it so that the `.get` method works by **not** putting underscored properties in the `_device_tuple` constructor., then when we call …

MAINT: Hidden signals

---

ophyd/signal.py

This defers grabbing the actual Signal object until init time.

ENH: allow 'derived_from' input do DerivedSignal to be a string

---

ophyd/device.py
ophyd/epics_motor.py
ophyd/ophydobj.py
ophyd/pseudopos.py
ophyd/pv_positioner.py
ophyd/signal.py

Reroute logging messages through loggers attached to instantiations of devices. This allows more detailed logging of individual device behaviors through complex scanning routines. Component devices use their `parent` log so that logic can be tracked through often complex nested component architecture. The highest level logger in the device will still start with `ophyd.` so `logging.getLogger('ophyd')` still gets all the log messages you received previously. 
I avoided changing any class that doesn't explicitly inherit from `OphydObject` so any log messages in the interface classes still go to module level logger. It would be nice to get these as well but I didn't want to break anything by assuming all implementations of the interface are on `OphydObj`. 
Closes #525

ENH: Individual Device logging

---

ophyd/epics_motor.py

Compare the alarm state at the conclusion of a move against the `tolerated_alarm` instead of a fixed `AlarmSeverity.NO_ALARM`. The operator will always be warned of an alarm but this change just modifies whether or not the alarm is of a high enough level to mark the move as failed. This allows alarm conditions to be ignored that do not affect the motor's ability to scan.
Closes #530

ENH: Flexible Alarm Handling in EpicsMotor

---

ophyd/areadetector/filestore_mixins.py
ophyd/sim.py

This requires no changes to bluesky, which just expects any Iterable and will be just as happy with a generator as with a tuple. The rationale for changing the implementation is to protect against accidentally introducing the assumption that this is non-lazy (i.e. something with a length) in the future. There are cases where a generator is useful, such as when datums are dynamically generated during collection. But returning a tuple or a list will continue to be accepted too.

REF: Use a generator in collect_asset_docs.

---

.gitignore
ophyd/__init__.py
ophyd/areadetector/plugins.py
ophyd/device.py
ophyd/epics_motor.py
ophyd/flyers.py
ophyd/mca.py
ophyd/ophydobj.py
ophyd/positioner.py
ophyd/pseudopos.py
ophyd/pv_positioner.py
ophyd/quadem.py
ophyd/scaler.py
ophyd/signal.py
ophyd/sim.py
ophyd/tests/test_areadetector.py
ophyd/tests/test_device.py
ophyd/tests/test_epicsmotor.py
ophyd/tests/test_hints.py
ophyd/tests/test_kind.py
ophyd/tests/test_mca.py
ophyd/tests/test_pvpositioner.py
ophyd/tests/test_quadem.py
ophyd/tests/test_scaler.py
ophyd/utils/_backport_enum.py

Closes #540 Closes #539 Closes #502 Closes #487 
It is possible we make poor life choices, but this seems to work and has a number of additional nice properties
- the ground truth of if a component is included in the `read` or `read_configuration` (or both!) walks of the Device tree is now held in the components
- it is now clear how to configure this at class definition time
- the old API of _setting_ `read_attrs` and `configuration_attrs` still works
- changing the state of a parent via `dev.child.kind = Kind.OMITTED` won't affect grand chlidren.
- leaf-nodes can be made hinted via `dev.child.leaf.kind = Kind.HINTED` 
- The many versions of `_default_*_attrs` still work as before
API breaks
- read_attrs / configuration_attrs will now contain all of the components touched when walking …

Component Kind

---

ophyd/device.py

@tacaswell 's fix of the slowdown we noticed. override `__iter__` to be lazy. Default is to call `__getitem__` [here](https://github.com/python/cpython/blob/master/Lib/_collections_abc.py#L879) which basically creates a new list calling `__internal_list` which walks the tree upon *every access*.

Added a lazy version of __iter__ method

---

ophyd/sim.py
ophyd/tests/test_sim.py

There isn't a convenient way in the library to test logic provided by `Device` subclasses. It can be done with `using_fake_epics_pv` but it tends to be awkward.
This PR introduces `make_fake_device`, which inspects a device class and creates a "fake" version of it with the same constructor, call signatures, etc. It does this by copying the `Component` objects and swapping the `cls` fields from `EpicsSignal` to `FakeEpicsSignal` and from `EpicsSignalRO` to `FakeEpicsSignalRO`, making a subclass with the fake signals. The fake signals are intended to do as little as possible to avoid adding failure points to tests unrelated to the real devices classes we are spoofing.
This is an idea I was throwing around at SLAC in https://github.com/pcdshub/pcdsdevices/pull/229.
I also make some minor …

ENH: make_fake_device factory function

---

ophyd/device.py

The __repr__ method returns a string that is to long and confusing, I have removed read_attrs and config_attrs from the string in order to reduce the complexity.

Remove read_attrs and config_attrs from __repr__

---

ophyd/areadetector/filestore_mixins.py

We encountered this error on a detector whose readable attribute returned an empty dict. This would help better traceback the issue. Without this, we just see "Nonetype is not subscriptable"

Added error reporting for no resource uid

---

ophyd/areadetector/plugins.py

This adds the set, read and describe attributes to the ROIplugin class. This allows the ROI regions to be 'set' and 'read' like normal positioners, and hence allows them to be included into 'log_pos' an 'baseline' readings as well as being set in 'mv(....)' plans.
This was added after seeing that a beamline had made some changes to allow this functionality in there startup file.

ROIplugin update to include 'set' attribute for ROI region

---

ophyd/device.py

This method was raising an `AttributeError` instead of returning `False` when something was not in the list e.g. `'not_a_real_signal' in device.read_attrs` would error out. I opted to check the full list rather than taking any shortcuts.
I ran into this when testing some of our older modules with `ophyd=1.2.0` that were checking if certain strings were in the `read_attrs` list. Is there a suggested way to check if something will be read if `read_attrs` is ever removed?

FIX: read_attrs/config_attrs backcompatibility __contains__

---

ophyd/sim.py

These don't relate to the delay function of the axis at all but
are useful to exercise all the kinds.

ENH: add config and ommitted components to SynAxis classes

---

ophyd/signal.py

Currently `ophyd` assumes you have a single floating point number as the value. This is not necessarily the case as `Signal` will be whatever you tell it.
This code simply mirrors the `data_type` and `data_shape` methods used in `EpicsSignal`.
`Signal` initializes itself as `None`. `None` is not a valid `data_type` therefore:
```python
signal = ophyd.Signal('signal')
signal.describe()
```
Raises an error. This same situation is true if the user puts any unacceptable data type into the signal.
Downstream clients like Typhon expect that `Signal` has an accurate description of itself. Currently if a user places a string in a `Signal` it tells us it is a number which then breaks when we convert it for display.
Closes #574

MAINT: Signal should describe itself

---

.travis.yml
ophyd/areadetector/base.py
ophyd/tests/test_areadetector.py
test-requirements.txt

This PR adds a method to ADBase that generates a plot of the asyn port diGraph using `networkx.draw_networkx` The new method takes in all `*args` and `**kwargs` that are available in  `draw_networkx` and  pases them through. It finds the diGraph using self.get_asyn_diGraph().

Adding a method to ADBase that generates a plot of the asyn diGraph

---

ophyd/sim.py

This ensures that if they are set with an integer they cast that to
float so that `describe` always returns the same datatype.

FIX: always treat motor positions as floats

---

ophyd/sim.py
ophyd/tests/test_sim.py

After submitting the `FakeEpicsSignal` and `make_fake_device` code a couple months ago, I used it to clean up the tests for the SLAC devices library, but noticed some things were missing.
This adds:
- `sim_set_enum_strs` so that you can get/set using the enum string as a real PV would behave
- some checks `EpicsSignal` was doing but this class was not
- `EpicsSignalWithRBV` to the base cases so that fake area detector classes are built correctly
- relevant tests for the above

ENH: Add enum spoofing to FakeEpicsSignal, fix some bugs

---

ophyd/signal.py
ophyd/tests/test_device.py

Noticed this while making a `typhon` widget for an `AttributeSignal`. When you call `.put` on your `AttributeSignal`it never runs it's subscriptions. I realize we won't get updated when the underlying attribute gets swapped out but it is nice to get updated when somebody writes using the `AttributeSignal` interface.
Was also curious how people felt about the ability to add a little metadata to these signals. (I'd do this in a separate PR, but since you have read this far). The idea is that we might want to add a little extra data to `.describe` but not subclass.
```python
class MyDevice(Device):
calculated_width = Cpt(AttributeSignal, attr='width_calc', desc={'units': 'mm'})
```

MAINT: AttributeSignal should run subscriptions

---

ophyd/device.py
ophyd/tests/test_device.py

Fix the (much-maligned) `.put` functionality of `ophyd.Device` in cases where the user did not use the Device-specific `DeviceTuple`.
I'm a bit surprised this never popped up before, but it was broken for all inputs where there was more than one signal. Incidentally, that also happens to be where it is useful - on a device composed of multiple components.

FIX/TST: Device.put for non-DeviceTuple values

---

ophyd/sim.py
ophyd/tests/test_sim.py

Adds a couple convenience functions for more easily working with fake devices.
`instantiate_fake_device`: creates a fake device class and instantiates it for you, making its best guess at keyword arguments
`clear_fake_device`: resets all components of a device (and its sub-devices) to specific values. This works around the default of `None` for all signals that causes problems with `.describe()`.

ENH: add instantiate_fake_device, clear_fake_device

---

ophyd/areadetector/plugins.py

`get` will return a tuple. Comparing this to a list will never return `True`.

FIX: Comparing list to tuple for invalid array_size

---

ophyd/signal.py
ophyd/sim.py

Closes #643 
In the issue, @ZLLentz brought up the following:
>  I agree with the intent of this issue, but we should also see if any of the features here could have use cases that we want to make explicit arguments.
The keywords in pyepics `epics.PV` are as follows:
```python
def __init__(self, pvname, callback=None, form='time',
verbose=False, auto_monitor=None, count= None,
connection_callback=None,
connection_timeout=None, access_callback=None):
```
I believe we are good as-is. Thoughts?

API: remove pv_kw from EpicsSignal classes

---

ophyd/areadetector/filestore_mixins.py

This PR adds a new filestore mixin that should be used to run an Area Detector HDF5_plugin in `Single` mode instead of `Streaming` mode. The result of this mode is that a new hdf5 file is created for every `trigger`.It also adds a second filestore plugin that mixes into this the `FileStoreIterativeWrite` plugin.
This was motivated by a custom plugin which has an array with one dimension determined only after running the plugin The result is that each `trigger` then creates a different sized array to the previous one, and so the `Streaming` mode which sets the array size prior to any `trigger`  did not correctly save the data.
This has been tested in the field as submitted here (NSLS-II, SIX beamline, rixscam detector, XIP plugin) and is working there.

add a filestore mixin to be used with AD hdf5 plugin in Single mode

---

ophyd/sim.py

We are creating a simulation with `SynGauss` as a base. However, it is quite annoying needing to construct a new instance each time we want to modify the shape of our gaussian. This makes the parameters available post class construction so that they can be modified / inspected later. 
I went ahead and also made sure `motor` and `motor_field` were available as well largely for completeness.

MNT: Ensure gaussian parameters are available after class construction

---

ophyd/__init__.py
ophyd/log.py

This duplicates the `bluesky.log.py` file to `ophyd.log.py` It adds a default logging handler to ophyd at import time and provides a convenience funciton `ophyd.set_handler`to configure that handler to adress common use cases. This brings it into line with blueksy and caproto.

ENH: add log.py and update __init__.py

---

ophyd/sim.py

This update is trying to fit bluesky test need. For more details, please check [here](https://github.com/NSLS-II/bluesky/pull/1127) for Dan's explanation 
Instead of use `TrivialFlyer` and `OldStyleTrivialFlyer`, `NewTrivialFlyer` and `TrivialFlyer` are used here which allow `TrivialFlyer` keep unchanged meaning. This would avoid updating any previous code use `TrivialFlyer`

MNT: Add NewTrivialFlyer with collect_asset_docs()

---

ophyd/signal.py
ophyd/tests/test_utils.py
ophyd/utils/epics_pvs.py

- the check in set_and_wait used to fail with
value error for arrays and the exception was going
to the debug log
- at TES we used list(...) to get around this
- Teddy updated Signal to correctly report it's type,
but the type sniffer did not correctly handle lists

ENH: fixes to Signal from working at TES

---

ophyd/areadetector/base.py
ophyd/areadetector/plugins.py
ophyd/device.py
ophyd/signal.py
ophyd/tests/test_areadetector.py

This introduces `NDDerivedSignal` a subclass of `DerivedSignal` to reshape a flat array into a shaped one based on either static values or other components of the class. This was made with the purpose of the supporting shaped image signals, but I believe it is general enough to apply to any situation where you have a flat array this is intended to be reshaped.
This is useful for a variety of reasons, my major motivation is for `typhon` which can not tell a flat array from an image without checking if we are looking at an `AreaDetector` class explicitly. However, this certainly makes things like a `LiveImage` callback far easier to write. 
Also closes #673, before `DerivedSignal.describe` used most of the original signals description. We now infer the `data_type` and `shape` from the value …

ENH: NDDerivedSignal

---

ophyd/areadetector/detectors.py

It must have been a copy-paste typo that `PerkinElmerDetector` used a cam plugin based on `LightFieldDetectorCam`. This PR fixes this issue.

FIX: use cam.PerkinElmerDetectorCam for PerkinElmerDetector

---

ophyd/scaler.py

`chname` is the EpicsSignal, `name` is a str and raises an exception here

FIX: ScalerCH

---

ophyd/log.py

I guess when the `log.py` was ported from bluesky via #664, the logger name wasn't changed accordingly. This PR corrects it.

FIX: correct logger name

---

ophyd/areadetector/filestore_mixins.py

Ophyd unconditionally tries to set the `capture` component of the TIFF plugin of the AD to `0` in https://github.com/NSLS-II/ophyd/blob/18de9724f0d9cf78f1a0e3abe3dd8da9408b6260/ophyd/areadetector/filestore_mixins.py#L427
However, this action is not supported when the TIFF plugin is in the "Single" file write mode, so that it results in the error `ERROR: capture not supported in Single mode`:
This PR attempts to workaround this situation.

FIX: Setting Capture has no effect in Single Mode.

---

ophyd/areadetector/base.py
ophyd/tests/test_areadetector.py

* Add a utility `devices_in_parent` to search through entire device lineage
* Make sure any references to `_sub_devices` are replaced with the `devices_in_parent`
Closes #635

FIX: Allow for nested plugins in AreaDetector

---

ophyd/__init__.py
ophyd/_caproto_shim.py
ophyd/_dispatch.py
ophyd/_dummy_shim.py
ophyd/_pyepics_shim.py
ophyd/ophydobj.py
ophyd/signal.py
ophyd/tests/test_signal.py

This PR aims to fix a callback-related issue created by the latest Signal refactor.
The Signal refactor intended to keep metadata information and values up-to-date with individual `.get()` and `.get_setpoint()` requests in `EpicsSignal`.  It also ran callbacks for value and metadata upon receiving new information.
DBR_CTRL Updates
----------------
First, note that EpicsSignal monitors using DBR_TIME on the control layer. If the `get()` requested a DBR_CTRL type by specifying `get(..., form='ctrl')`, for example, units and such would be updated internally.  There is no `DBR_` type which encapsulates all of the possible metadata.
The issue
---------
Callbacks being run by `.get()` on every call meant that an infinite recursionscenario was very easy to run into.
I discovered this while …

FIX: monitor + get*() issue

---

ophyd/tests/conftest.py

This makes it possible for other libraries (e.g. suitcases) to reuse some
ophyd fixtures (e.g. ``hw``) without installing all of the optional caproto
test dependencies. This is no small thing: the set of of depedencies we avoid
having to manage includes curio, trio, special attr verison for trio, asv,
pytest-benchmark.

TST: Hide caproto imports.

---

ophyd/sim.py

The event-model expects path semantics to be one of
``{'posix', 'windows'}`` but ``os.name`` returns ``'nt'`` on Windows.

FIX: Use a valid path semantics choice.

---

ophyd/tests/test_epicsmotor.py

This bug exists at some points of master, was hit by APS, and has
already been fixed by @klauer.
This simulates what happens if you monitor as motor in bluesky.

TST: Add a test of recursive callbacks

---

.codecov.yml

This adds a configuration file that we have had in bluesky and other
repos for awhile now. It silences codecov giant comments, while still
leaving codecov's X's or checkmarks in the block "checks" above the
Merge button.

CI: Silence codecov comments.

---

ophyd/tests/test_ophydobj.py

I noticed some warnings leaking out of the tests because we use a
deprecated API in the tests.
I have wrapped test of the API in `pytest.warns` and added a new test to
check the new API as well.

TST: Test old and new status API.

---

ophyd/__init__.py
ophyd/ophydobj.py
ophyd/tests/test_ophydobj.py

At various times it has been proposed to "auto-register" ophyd objects
in order to maintain a global registery of devices. We have avoided
making OphydObj aware of all its own instances because this could have
weird implications and generally feels like an unusual design in Python.
But we could allow downstream code to sign up to be notified each time
an OphydObj is instantiated. Each subscriber will get one notification,
and they can keep a strong or weak reference if they like, as needed.
<hr />
This suggestion is fully due to @tacaswell and I may or may not have
implemented it exactly as he envisioned. I need to refer to it in
another discussion so I have sketched it here.

ENH: Add register_instance.

---

setup.py

This is now part of our standard configuration for new projects, but it was
never added to ophyd.

BLD: Add python_requires.

---

ophyd/sim.py

This is to make `no_hints` tests passing in Bluesky.

ENH: reconfigure hints for sim motors

---

ophyd/signal.py

This is to be more specific which device has a second `set` call.

ENH: specify for which device another set call is issued

---

ophyd/areadetector/cam.py

support for [ADLambda](https://github.com/areaDetector/ADLambda) [X-Spectrum Lambda 750K](https://x-spectrum.de/products/lambda-350k750k/) area detector
We also have support for [the plugin chain we use now](https://github.com/aps-8id-trr/ipython-8idiuser/blob/master/profile_bluesky/startup/25-areadetector.py#L23-L72).  That plugin chain is likely to be redeveloped in the next year and might not be useful in ophyd, other than pedagogical value.

ENH add Lambda750kCam

---

ophyd/signal.py

A glaring mistake in the latest refactor... Likely just the tip of the iceberg!

FIX: EpicsSignal not showing disconnected

---

test-requirements.txt

Some of caproto's *optional* dependencies are very experimental:
in particular, ``curio``, ``trio``, and ``asks``. They sometimes
introduce dependencies on bleeding-edge versions of things (most
recently, ``attrs``) that can cause packaging headaches in our other
downstream libraries. These optional requirements should not propagate
into ophyd.

Do not depend on caproto's experimental dependencies.

---

ophyd/device.py
ophyd/tests/test_device.py

Make sure we set the state back if something raises inside of the
context block.

MNT: make *_lazy_wait_connection context managers more paranoid

---

ophyd/device.py

Just an idea - see docstring in diff for the example.

REF/ENH: do not require `self` for FormattedComponent

---

ophyd/signal.py
ophyd/sim.py

This PR restores SignalRO which was being heavily used by Typhon for tests.
Closes #780 
Attn. @klauer

FIX: Restore SignalRO

---

ophyd/ophydobj.py
ophyd/signal.py

Per @prjemian, there is a decades-long bug in the EPICS servers that causes IOCs to sometimes ignore read requests, even though the specification requires them to respond. Reportedly, SPEC works around this by simply retrying. This is a little scary, because if the IOC is suddenly not abiding by the specification one could worry that it could be giving wrong data.
We have observed this intermittently at NSLS, typically in the context of Area Detector and at least once with a Scaler. At APS (particulartly 8ID) they have observed it significantly more. Anecdotally, this server issue seems to be easier to hit with hard IOCs than soft IOCs, which may explain why it is more common at APS than NSLS.
As a compromise, ophyd will allow users to opt in to retries. Default settings can be applied at …

Make timeouts more configurable.

---

ophyd/status.py

tqdm does not like things that are out of range and correctly think it
is the clients problem to ensure this invariant.

MNT: clip progress fraction to [0, 1] to be safe

---

ophyd/status.py
ophyd/tests/test_status.py

It should never have been possible to set `status.done` directly. This
PR makes doing so issue a warning. In the N+1 release we should remove
the setter entirely.

Deprecate settable done attribute.

---

doc/source/architecture.rst
doc/source/conf.py

Explains why everything in ophyd has 3 names.

DOC: add text version of 3-names spiel

---

ophyd/_pyepics_shim.py

This is a second pass at https://github.com/bluesky/ophyd/pull/774 (which was reverted) addressing the review comments that didn't get addressed before the merge of #774.

Resolve #773 again.

---

ophyd/signal.py
ophyd/tests/conftest.py

In #788 we added the ability to control the default timeout (and
per-signal PV timeout).  For unclear reasons some IOCs can take an
unexpectedly long time to service read requests and this knob gives us
the ability to accept that delay rather than failing the `get` which
returns `None` which tends to cause issues with down stream code.
That enhancement was built on top of a number of other
changes (including the machinery to know if any Signals have been
instantiated yet and an overhaul of EpicsSignal internals) which makes
it impossible to directly back-port that change to the 1.3.x branch.
Instead, we hard-code the default timeout to 10s.  This will increase
how long it will take for us to fail if the server truly has become
non-responsive, but will greatly reduce the number of …

HACK: set read timeout unconditionally to 10s

---

.travis.yml
run_tests.py

The ``run_tests.py`` just runs ``pytest`` and does nothing else; it
amounts to obsfuscation and should be removed.
The commit that added this file in October 2017
(0d0c9b52df1ac91b781ad83178f5634a0fdf64c1) was mine, and it had the
commit message
TST: Add run_tests.py like our other packages have.
Nowadays we tend to invoke ``pytest`` directly and use the pytest's
standard configuration file ``pytest.ini`` to apply any customizations
to its behavior. I think this approach is better because it is (1)
standard and (2) more constrained than a generic Python script. It makes
it clear in ``.travis.yml`` what program is being run.

Remove run_tests.py

---

.travis.yml
ophyd/log.py
ophyd/ophydobj.py
ophyd/signal.py
ophyd/sim.py
ophyd/status.py
ophyd/tests/test_log.py

This PR proposes
- automatic logging configuration on import of ophyd/log.py - taken from caproto with one change described below
- logging calls in the Signal class
The logging configuration in caproto is used as a template, but the file handler has been changed to TimedRotatingFileHandler set to rollover to a new file every week and to keep the last four log files.

add logging to Signal

---

.travis.yml
setup.py

Ophyd has long included a simple "databroker handler" for numpy pickle files in `ophyd.sim` for testing and teaching purposes.
This PR hooks into the new discovery mechanism for handlers using entrypoints ([documentation](https://blueskyproject.io/event-model/external.html#handler-packaging)). Note that this does not introduce a databroker dependency of any kind. Its effect is to add a line to `entry_points.txt` inside the installation directory that standard Python tooling can discover. For example, a utility function in databroker can find it like this:
```py
In [2]: databroker.core.discover_handlers()                                                                                                                                                   
Out[2]: 
{'NPY_SEQ': …
```

Make 'NPY_SEQ' handler discoverable.

---

ophyd/_pyepics_shim.py
ophyd/signal.py

This makes the timeout for a *write* configurable on a per-put and
per-Signal basis. It uses a similar pattern to what we did for read and
connection timeout in #788.
At SST, we were hitting a hard-coded timeout of 30 seconds (somewhere
in caproto or ophyd, I now don't recall...) and the motion of their mono
can sometimes take longer. With these changes, we could set
``write_timeout=180.`` in anticipation of lengthy motions.

Support a Signal write_timeout pass to put.

---

ophyd/_caproto_shim.py
ophyd/_dispatch.py
ophyd/_pyepics_shim.py

A torn-down logger can cause these messages to blow up as tracebacks at the end of a pytest session

MNT: remove annoying teardown messages

---

ophyd/device.py

Touches docstrings only.
Closes #766.
Related to #752 where we discuss possible changes to these methods.

Note that walk_ instance methods are experimental.

---

ophyd/signal.py
ophyd/tests/test_areadetector.py
ophyd/tests/test_signal.py
ophyd/tests/test_sim.py
ophyd/tests/test_timestamps.py

This restores the behavior for ophyd <= 1.4.
While properties that may take an (arbitrarily) long time are not
great, silently changing the semantics of the property has too high of
a chance of causing hard to detect bugs in beamline code.
xref #814
I can cook up some tests for this if required (basically get a real PV to talk to, make an epics signal, side-band change it, assert `obj.value` changed).

API: make Signal.value sometimes defer to self.get()

---

doc/source/conf.py
doc/source/debugging.rst
doc/source/index.rst
ophyd/log.py

The first commit copied the logging documentation from bluesky as is. The
second commit makes the necessary changes to account for library-specific
details.

Add logging documentation

---

ophyd/areadetector/filestore_mixins.py

This is found with @mrakitin at NSLS-II RSOXS beamline when the collection is done on the Windows machine, and the detector is on a Linux one.

FIX: correct path semantics behavior

---

ophyd/epics_motor.py

Fixes #802 by connecting to EPICS motor record soft limits (`.HLM` and `.LLM`) and keeping ophyd `EpicsMotor` object synchronized with EPICS.
Also supplies two methods for call compatibility with SPEC.

ENH #802 connect EPICS soft motor limits

---

setup.py

Copied from our cookiecutter.
Tested with `python2 setup.py sdist`.

Use nice error message if Python too low.

---

ophyd/tests/test_signal.py

Encountered a random test failure on TravisCI on #829. 
This is due to the free workers being quite slow, so increasing the timeout on this test a bit.

Increase test wait time to avoid failure on travis

---

ophyd/sim.py
ophyd/tests/test_sim.py

It should be possilbe to call `describe()` any time after an object is
intialized. This fixes a regression from 1.3.x and adds a test.
We make an exception for area-detector-like objects until ophyd 1.6.0
applies a re-think to how `describe()` works on those to make it just
like everything else.
Thanks @lsammut for the bug report.

Ensure that describe() works on ophyd.sim.hw objects.

---

ophyd/mixins.py
ophyd/positioner.py
ophyd/status.py
ophyd/tests/test_epicsmotor.py
ophyd/tests/test_ophydobj.py
ophyd/tests/test_status.py
ophyd/utils/__init__.py

Addresses Point 1 of #825.
```py
In [1]: def f(): 
...:     print("BANG!") 
...:                                                                                                                                                                                       
In [2]: def g(status): 
...:     print(f"BANG! from {status}") 
...:                                                                                                                                                                                       
In [3]: import ophyd                                                                                                                                                                          
In [4]: thing = ophyd.Device(name='thing') …
```

Give callbacks access to status

---

ophyd/areadetector/trigger_mixins.py
ophyd/device.py
ophyd/flyers.py
ophyd/sim.py
ophyd/status.py
ophyd/tests/conftest.py
ophyd/tests/test_log.py
ophyd/tests/test_ophydobj.py
ophyd/tests/test_positioner.py
ophyd/tests/test_pvpositioner.py
ophyd/tests/test_status.py
ophyd/utils/errors.py

This is a fully-backward-compatible implementation of (3) and (4) in #825.
Adds methods:
```py
set_exception(exc)
set_finished()
exception(timeout=...)
wait(timeout=...)
```
The done state is now implemented internally in terms of a `threading.Event` instead of a boolean. The success state is now implemented internally in terms of a stashed exception. A generic exception is used when we are given `Status(sucesss=False, ...)` or `status._finished(success=False)` and the Device has thus not told us the cause of failure.
The polling logic in the timeout thread and in the top-level function `wait(status, timeout, poll_rate)` uses `threading.Event.wait(timeout)` instead.
Example:
```py
In [1]: import ophyd …
```

Refactor Status around a threading.Event and add methods.

---

ophyd/status.py
ophyd/tests/test_status.py

Closes #839
These are harmless, but I think worth deprecating and removing in the name
of simplicity.

Deprecate Status(..., done=True)

---

ophyd/signal.py

Fixes #834
Replaces #842
`__del__` turns out to be unreliable and causes issues when interacting with specific versions of pyepics, epics-base and libca during teardown. This is because the order that things are destroyed in is inconsistent and implementation specific.
`weakref.finalize` is used instead to avoid this problem. Thanks @danielballan for suggesting it!

Use finalize instead of __del__ to tear down Signals

---

ophyd/areadetector/base.py
ophyd/pseudopos.py
ophyd/tests/test_signal.py
ophyd/utils/__init__.py

Cleanups to avoid warnings due to the new expected signature on Status done callbacks.

Mnt status warnings

---

ophyd/epics_motor.py

Due to #847, `subscribe` will block waiting for connection for epics signals. Recently in #802 two `subscribe` calls were added in `EpicsMotor.__init__`. This means that creating `EpicsMotor` instances now blocks on connection, which isn't desirable.
A quick way around this is to set `auto_monitor=True` on the signals that we plan to monitor during `__init__`, this allows the subscriptions to be set without the waiting for connection that is normally required to turn on signal monitoring.

MNT: auto_monitor signals that will be subscribed to

---

ophyd/areadetector/base.py
test-requirements.txt

I came across this issue while debugging https://github.com/pcdshub/typhos/issues/288.
The problem here is that when the DerivedSignal source (in this case ArrayData_RBV) is connected, the VALUE callback is invoked many times but the attributes of NDDerivedSignal such as `_shape` and `_num_dimensions` were not yet set which then generates an issue if `describe` is invoked at the NDDerivedSignal as the `_readback` was never set as the callback for Value triggered by ArrayData_RBV changes was never successful.
That results into wrong metadata at the describe.
Steps to Reproduce
--------------------
```python
import time
import logging
logging.basicConfig(format='%(levelname)s:%(message)s', level="ERROR")
logger = logging.getLogger("ophyd")
logger.setLevel("ERROR")
from ophyd import …
```

FIX: Set attributes before invoking super at NDDerivedSignal

---

doc/source/device-overview.rst

Came to [this page](https://blueskyproject.io/ophyd/device-overview.html?highlight=trigger#trd) looking for a clear description of `trigger()` for a tutorial.  As it reads, the section does not connect the dots for a newcomer.  This change makes a quick summary and connects to [existing documentation](https://blueskyproject.io/ophyd/generated/ophyd.device.BlueskyInterface.trigger.html?highlight=trigger) for more details.  Same for `read()` and `describe()` since they are in the same section.

Help newcomers to learn what trigger() does

---

.flake8
doc/area_detector/gen.py
ophyd/__init__.py
ophyd/areadetector/__init__.py
ophyd/areadetector/filestore_mixins.py
ophyd/epics_motor.py
ophyd/signal.py
ophyd/sim.py
ophyd/tests/test_areadetector.py
ophyd/tests/test_sim.py
ophyd/utils/epics_pvs.py

It was not quite correct and is causing dead-locks in jupyter notebooks.  Rather than attempt to discover and attach to an asyncio loop, always use threads to implement delays.
This should un break the tutorials notebooks.

MNT/API: remove the asyncio integration in ophyd.sim

---

ophyd/areadetector/common_plugins.py

Looks like this started out as a dictionary and turned into a `set` by mistake, losing the sensible component name ordering provided.
Before:
```python
In [4]: class MyDetector(ophyd.SimDetector, ophyd.areadetector.common_plugins.CommonPlugins_V32):
...
In [5]: MyDetector.component_names
Out[5]:
('scatter1',
'roi1',
'roi2',
'stats4',
'roistat1',
'fft1',
'cc2',
'cc1',
'netcdf1',
'proc1',
'stats3',
'nexus1',
'hdf1',
'gather1',
'roi4',
'roi3',
'stats2',
'jpeg1',
'tiff1',
'attr1',
'trans1',
'over1',
'stats1',
'cb1',
'stats5',
'configuration_names',
'cam')
```
After
```
In [1]: MyDetector.component_names
Out[1]:
('attr1',
'cb1',
'cc1',
'cc2',
'fft1',
'gather1',
'hdf1',
'jpeg1',
'netcdf1',
'nexus1',
'over1',
'proc1',
'roi1',
'roi2',
'roi3',
'roi4',
'roistat1',
'scatter1',
'stats1',
'stats2', …
```

FIX: ordering of components for CommonPlugins classes

---

ophyd/_pyepics_shim.py
test-requirements.txt

Updates pyepics pin to 3.4.2 in the pyepics shim and `test-requirement.txt`, for the libca teardown crash fix.

Update required pyepics version

---

doc/source/debugging.rst

Replaced three instances of `from ophyd import config_ophyd_logging` 
by `from ophyd.log import config_ophyd_logging`

DOC: corrections in example code (logging)

---

doc/source/release_notes.rst
ophyd/signal.py

This does not actually fix anything, but it seems a step closer to "good practice" so it may be worth merging for its own sake.
Notice that the original in `master` makes reference to the instance state when the finalizer is _run_ whereas this grabs the attributes it needs when the finalizer is _defined_ and then makes no further reference to `self`.
My reading of this line in the weakref docs
> A more robust alternative can be to define a finalizer which only references the specific functions and objects that it needs, rather than having access to the full state of the object:
is that to make full use of the benefits of `weakref.finalize` over `__del__`, the finalizer should avoid closing over `self`.

Avoid closing over self in the finalizers.

---

ophyd/sim.py

This PR addresses the issue https://github.com/bluesky/ophyd/issues/876
The objects `rand` and `rand2`, which are instances of the class `SynPeriodicSignal`, are created at the time of importing of `ophyd.sim`. The constructor for the class `SynPeriodicSignal` is automatically starting a background thread for each object even if the object is not used in simulation. In this PR a new method `start_simulation` is added to `SynPeriodicSignal` to start the background thread before the object is used. The constructor now is not creating the thread. Instead, the method has to be called manually in order to start periodic updates of the PV. This breaks the existing API and may prevent existing simulation code from running correctly.
In order to provide backward compatibility, a number of methods …

'ophyd.sim': prevent threads for unused objects ('rand', 'rand2') from starting automatically

---

ophyd/__init__.py
ophyd/areadetector/__init__.py
ophyd/utils/__init__.py
ophyd/utils/startup.py

This PR follows the discussion with @danielballan regarding the default behavior of logging: the default behavior of the logger should be to print all logged messages with levels `warning` and above. Currently, the logger is set to use `NullHandler` at the time of importing Ophyd packages. This results in no log messages printed unless other handers are added, which needs to be done explicitly in the code. 
Changes: the line that adds `NullHandler` is deleted, therefore no handlers are added to the Ophyd logger during import.

Do not set the default logging handler ('NullHandler') at import

---

ophyd/device.py
ophyd/mca.py
ophyd/tests/test_device.py
ophyd/tests/test_mca.py

This is likely a side-effect of changing from using a full meta-class
to `__init_subclass__`.

FIX: mixin classes that have components must inherit from Device

---

ophyd/areadetector/trigger_mixins.py

Review of how triggering works now:
When staged, we set up a subscription to the `self._acquisition_signal` which is removed when we are unstaged. The subscription calls the method `self._acquire_changed`, which operates on the state `self._status`. When `self._status is None`, `self._acquire_changed` becomes a no-op.
It looks like we _intended_ to reset `self._status` to `None` when trigger completed, so that any subsequent calls to `self._acquire_changed` would be a no-op. [But I can't find where we actually _do_ that, so this PR adds it.]
There is another problem here that this PR does not address. It is possible to trigger the device twice without waiting for the first trigger to complete. The result would be that the status object corresponding to the first trigger will never be …

Reset status to None when trigger completes.

---

ophyd/scaler.py

fixes #869 (chan01 was always selected even if empty name) and fixes #870 (makes `None` a default parameter: change the arg into a kwarg)

ScalerCH.select_channels default parameter

---

ophyd/epics_motor.py

It looks like the ophyd `master` branch has been failing CI ever since
https://github.com/bluesky/ophyd/pull/886 was merged. This rights it.

Fix flake8.

---

ophyd/signal.py

This line dominates `bluesky.log` and generated 9 MB of log data in
about a minute at SMI. This should be DEBUG level.

One particular log line in ophyd is too verbose.

---

ophyd/areadetector/cam.py

We should have been capturing `num_images`! I notice that we do capture
`num_exposures`, which is a counter of how many images have been acquired so
far, whereas `num_images` is the total that *will* be acquired in this batch.
We might consider removing `num_exposures` to avoid confusion---I don't think it
very useful to capture it.

Capture num_images as config.

---

ophyd/signal.py

provide float format specifier where previously implied (as integer)

---

doc/source/status.rst
ophyd/status.py

When the subscriptions are run, `value` and `old_value` are always passed in by keyword, not positionally. This happens in the ophyd layer and is not dependent on the control layers (pyepics, caproto) so we can be sure of it. Thus, their order does not matter.  This created a recent concern when it was discovered that some callbacks had signature `f(value, old_value, **kwargs)` while other had signature `f(old_value, value, **kwargs)`. The documentation should be clear on this point, and might as well require `f(*, value, old_value, **kwargs)` to be future-proof against some caller than attempts to pass in arguments positionally.

Correct documentaiton about SubscriptionStatus callback signature.

---

ophyd/areadetector/__init__.py
ophyd/areadetector/filestore_mixins.py
ophyd/areadetector/paths.py
ophyd/areadetector/plugins.py
ophyd/signal.py
ophyd/tests/conftest.py
ophyd/tests/signal_ioc.py
ophyd/tests/test_areadetector.py
ophyd/tests/test_epicspath.py
ophyd/tests/test_signal.py

Docstrings and cleanups would follow if this is deemed reasonable.
Basic idea is that on a `Device` level (specifically `FilePlugin`) we should be specifying a `Cpt(EpicsPathSignal, 'FilePath', path_semantics='nt')` instead of a regular `EpicsSignal`. This would then take care of `set_and_wait_path` for us.
I believe the base `EpicsSignal` should be more easily customizable to allow such things without massive copy/pasting, but opted to keep changes minimal for this proof-of-concept.
Notes
* Alternative to https://github.com/bluesky/ophyd/pull/703
* `_ensure_trailing_slash` could then be removed, and classes would be modified to use this.
* This would need changing as well: https://github.com/bluesky/ophyd/blob/master/ophyd/areadetector/filestore_mixins.py#L432 (not sure why we aren't …

ENH: add EpicsPathSignal

---

ophyd/signal.py

This is specifically for PDF, who are blocked on upgrading until the xpdacq
team removes their usage of `.value` from the codebase.

Add hook to silience .value warning.

---

ophyd/tests/signal_ioc.py

This bug was introduced recently in #749. It was my oversight.

Add missing return  value in test IOC.

---

ophyd/areadetector/plugins.py

This is a work in progress PR that tries to address the issue I described here: https://github.com/bluesky/ophyd/issues/911
Essentially, certain detectors use the typical `NDFile` PVs to perform direct I/O via the vendor API rather than the areaDetector plugins - this is often the case for max-speed modes on high speed detectors (ex. Eiger). As a result, I broke off most of the signals defined by `FilePlugin` into a new `FileBase` class, and had `FilePlugin` extend from it. Then, if detectors need, they could extend the `FileBase` class. 
I am marking this as a WIP, since I would like some feedback, and to perform some real world tests.

WIP - Introduce new FileBase class for use with FilePlugin + detectors that have direct disk write access

---

ophyd/signal.py

Changes to fix #925.  Expected the `EpicsSignal.set()` method to use the signal's `timeout` attribute.  This PR will make that happen.

EpicsSignal.set() timeout should default to EpicsSignal.timeout

---

ophyd/_dispatch.py

This removes a log message that I added and have since regretted.
The use of this message is to detect if event-proessing queues
are getting backed up, more or less akin to when caproto logs "high load"
messages. It is not necessary to log "low load"; omission is sufficient.
I added this in the first place because I wanted to ensure that the loop
was _running_ but that kind of debug activity is better handled by prints
as needed and should not have been merged into the main branch.

Do not log where EventDispatch queues are empty.

---

ophyd/signal.py
ophyd/sim.py

Ophyd is very noisy at the INFO logging level, including at import time. In the last week, both Michael Sutherland (a user) and @tacaswell have bumped into this and been thrown by it. Quick comments:
* At beamlines we don't generally put INFO-level logging in the stderr, but it's apparently not uncommon for users or beamline staff to do this, so INFO level (or higher) should be used with discretion.
* The intent of the `control_layer_log` is to do the logging that we _wish_ pyepics did. (Eventually we'll add that pyepics, perhaps.) It's in a separate logger so that it can be separately filtered. In this PR, I move something from `log` to `control_layer_log` and turn the level of all `control_layer_log` calls to DEBUG.
* For some reason `SynSignal` logged aggressively --- including …

Adjust signal logging

---

ophyd/signal.py

The "factory default" of `write_timeout`, set at import time, is `None`. In the signature of `set_defaults(...)` the default value of `write_timeout` is, arbitrarily, `2`. This means that calling
```py
EpicsSignalBase.set_defaults()
```
with no arguments changes the default value of `write_timeout` from `None` to `2`. This doesn't feel right. I have changed the signature to `set_defaults(..., write_timeout=__default_write_timeout)` and so on for the other parameters. That way, if we change the factory defaults someday, everything will stay in sync.
Note that, as usual, the docstring shows the concrete values, so the user can easily see what the default values actually are:
```
In [4]: EpicsSignalBase.set_defaults?
Signature:
EpicsSignalBase.set_defaults(
*,
timeout=2.0, …
```

Make default values of set_defaults consistent.

---

ophyd/epics_motor.py
ophyd/signal.py

This is code notes from a discussion with @prjemian and @danielballan which does to seperate things:
- Tell EpicsMotor to automonitor more things (which should drastically speed up `mtr.read_configuration()`
- re-threads `EpicsSignal.get(..., use_monitor=True)` back through to the control layer layer + sets a per-Signal default (which tracks auto-monitor).

Enh use monitor

---

ophyd/areadetector/cam.py
ophyd/areadetector/detectors.py
ophyd/areadetector/plugins.py

We noticed in https://github.com/bluesky/bluesky-browser/pull/36
that area detectors have been reporting the wrong shape in
``describe()``. For a given image ``arr`` referenced by ``read()[data_key]``
we expect ``describe()[data_key]['shape']`` == ``arr.shape``.
Currently ``describe()[data_key]['shape']`` is ``(x, y, 0)``. To match
the ``arr.shape``, it should be ``(num_images, y, x)``. This PR changes
the shape to make it correct.
Downstream tooling will need to cope with both, unless/until we sort out
how to do data migrations. The addition of version metadata to the
RunStart document in bluesky 1.6.0 may help with this.

Fix 'shape' reported by describe().

---

ophyd/areadetector/filestore_mixins.py

As explained in the comment, the `FileStoreHDF5` class has been recording its `num_capture` signal as the number of frames that will be captures for a given acquisition. The _correct_ behavior is to interpret `num_capture=0` as a special case because that means "Capture as many as you receive." In that case, our best guess (really an upper bound) is `num_images` from the detector's camera.
Closes #934

Interpret num_capture=0 correctly.

---

ophyd/epics_motor.py

Very small thing I noticed today: `HLS` and `LLS` use `EpicsSignal` when they should be using `EpicsSignalRO`. This was found when `typhos` confusingly decided to make writable widgets for limit hit state.
Ref: https://epics.anl.gov/bcda/synApps/motor/motorRecord.html#Fields_limit

MNT: motor record limits switch states are read-only

---

conftest.py
ophyd/signal.py
ophyd/tests/conftest.py
ophyd/tests/test_issue944.py

EpicsSignal with `string=True` kwarg should result in `dtype='string'` from `.describe()` method, to fix #944.

Resolve TypeError when using EpicsSignalBase.set_defaults()

---

ophyd/areadetector/cam.py

This was introduced in #919, fixing it after tests at AMX with @JunAishima, @dalekreitler-bnl, @AbbyGi, and @MikeHart85.

Fix EigerDetectorCam's photon_energy component's PV suffix spelling

---

ophyd/sim.py

Return `self.name`(instead of 'stream_name')  in MockFlyer `describe_collect` method. This will show the flyer name and prevent ambiguation when running multiple flyers.

Update MockFlyer in sim.py to return self.name in describe_collect

---

ophyd/areadetector/plugins.py

Adds `create_directory` signal to all AD file writers to fix #728 and close #938.
Needs to be set to `None` in subclasses for plugins that do not have this feature.  Perhaps that is AD <2.2.

add create_directory signal to standard AD support

---

ophyd/signal.py

We struggled quite a lot for the last couple of days of the deployment at NSLS-II, as it wasn't possible to set the connection timeouts using [`.set_defaults()`](https://github.com/bluesky/ophyd/pull/926). The monkey-patch we ended up applying was https://github.com/NSLS-II-ESM-1/profile_collection/blob/b7a67bdf181089836bd52764cf2f691b62339c3a/startup/01-base.py#L3-L27. This PR should provide a proper fix.
The connection timeout was set via:
```py
EpicsSignalBase.set_defaults(connection_timeout=0.5)
```
in an IPython startup file.
Used ophyd 1.6.0:
```py
[TerminalIPythonApp] Running file in user namespace: /home/mrakitin/.ipython/profile_collection/startup/02-olog_templates.py
[TerminalIPythonApp] Running file in user namespace: /home/mrakitin/.ipython/profile_collection/startup/03-olog_in …
```

Properly propagate connection_timeout from .set_defaults()

---

ophyd/scaler.py

For the scaler attributes `update_rate` & `auto_count_update_rate`, apply consistency to the setting of their `kind` kwarg.  Per discussion, this change will close #964, applying `omitted` to creation of these attributes.
Affects `EpicsScaler and `ScalerCH` classes.

MNT #964 apply consistency to update_rate & auto_count_update_rate

---

ophyd/tests/test_utils.py
ophyd/utils/epics_pvs.py

If `signal.get` returns None (which pyepics will sometimes do) and tolerances
are in use, passing `None` through to numpy will cause numpy to choke.
We were already implicitly re-trying in the non-tolerance case.
Encountered this in the wild at PDF over the weekend.

FIX: protect against a failed reading in set_and_wait

---

ophyd/signal.py

There's some legacy code running around in LCLS that is still misbehaving and sending various kwargs up to Signal.put. This quick edit made it much easier to track them down.
Pros: easier to resolve warnings
Cons: harder to filter warnings

MNT: expand signal put warning for context

---

ophyd/tests/test_utils.py
ophyd/utils/epics_pvs.py

The change in #972 (to make sure we did not accidentally feed None to numpy)
also made it impossible to set a (soft)Signal to None.
While there may or may not be a good case for doing this, it is implicitly
tested in bluesky so restore the functionality.

FIX: re-enable setting a Signal to None

---

requirements.txt
scripts/collect_ad_boilerplate.py

I'm not sure if this should live in this ophyd repository, but essentially this script allows for generating a bunch of boilerplate for new Detector and Cam classes by simply parsing the `.template` files for a specified areaDetector driver. To get an idea of what it does, you can take a look at a PR I am making adding the generated classes (with some minor hand-done fixes after) to add ADPICam detector and cam classes.
The ADPICam driver: https://github.com/areaDetector/ADPICam
I think long term this script will be replaced by some other, better, solution, like utilizing [PVI](https://pvi.readthedocs.io/en/latest/) from Diamond, but for now this should really simplify adding support for any new drivers.

Add simple script for helping generate boilerplate detector and cam classes

---

ophyd/__init__.py
ophyd/tests/test_signal.py
requirements-docs.txt

`SignalRO` is now imported by 'ophyd.__init__.py' 
so that it is available when importing `ophyd`
```python
from ophyd import SignalRO  # This now works
from ophyd import *  # ...so does this
```

Fix #990: Import 'SignalRO' with 'ophyd'

---

ophyd/sim.py
ophyd/tests/test_units.py
ophyd/units.py
requirements.txt

Summary
----------
* Fixes metadata keys on `FakeEpicsSignal`
* Fixes `put()` kwargs on `FakeEpicsSignal` to avoid frustratingly-common deprecation warnings
* Adds `UnitConversionDerivedSignal` with small test suite.
Closes #894 
Example
---------
This can be used as a device component like follows:
```python
setpoint = Cpt(UnitConversionDerivedSignal,
derived_from='component_name_to_convert_from',
derived_units='s',
original_units='ns',
kind='hinted',
doc='Setpoint which handles the conversion.',
limits=(-10e-6, 10e-6),
)
```
What does this do?
* The above would use `self.component_name_to_convert_from` and proxy methods such as `.read()`, `.describe()`, and value/metadata subscriptions (as does the original `DerivedSignal` for those unaware).
* The instantiated signal would apply unit …

ENH: add unit conversion derived signal from pcdsdevices

---

ophyd/areadetector/filestore_mixins.py

This PR adds the `create_directory` component to the `stage_sigs` of the `FileStorePluginBase` class, so that the requested directory can be created by the AreaDetector. See https://github.com/NSLS-II-SIX/profile_collection/pull/36 for the original implementation, ported to upstream here.

AD: add "create_directory" component to stage_sigs

---

ophyd/epics_motor.py

If the user puts in a bad value to `EpicsMotor.set_current_position`, this method can abort before restoring the `.SET` field (`set_use_switch`) to the normal value of `0` (`Use`), leaving it at the value of `1` (`Set`). This can cause confusion when someone tries to move a motor manually later, only for the position to be set instead of used.
This is just a simple try/finally block, we still raise the exception caused by the bad input but we clean up after ourselves.

MNT: set_current_position basic error handling

---

ophyd/areadetector/cam.py

-  this is a writeable PV when probed with `cainfo`, so it should not be RO
Example from FMX at NSLS-II:
```bash
$ cainfo XF:17IDC-ES:FMX{Det:Eig16M}cam1:SequenceId
XF:17IDC-ES:FMX{Det:Eig16M}cam1:SequenceId
State:            connected
Host:             xf17id2-ioc2-1723.nsls2.bnl.local:41309
Access:           read, write
Native data type: DBF_LONG
Request type:     DBR_LONG
Element count:    1
```

make AD Eiger SequenceId a writeable PV

---

docs/source/reference/builtin-devices.rst

Fix #591 (from 2018) and finally reveal the `ScalerCH` class in the documentation.  Also update the URLs to the EPICS synApps `scaler`, since in the interim, it has been moved out of the synApps `std` module.

DOC #591 add ScalerCH docs

---

ophyd/areadetector/base.py

Error message was showing the expected length (which always matched the shape) instead of the actual length (which triggered the error when it didn't match). Fixed to show actual length.

Fixed error message in NDDerivedSignal.inverse

---

requirements-dev.txt
requirements-test.txt
requirements.txt
scripts/collect_ad_boilerplate.py

We don't have `requirements-dev.txt` file in this repo, so I moved it to the best match `requirements-test.txt`.
Closes https://github.com/bluesky/ophyd/issues/1011.

PKG: move `inflection` package from requirements.txt

---

ophyd/signal.py

In many of my plans at BMM, I move many motors with a single `mv()` command.  Without identifying the motor in question, it is very hard to know which motor is the one triggering the outside-of-limits message.  This adds `self.name` to the error message.  Still not  perfect solution in that it adds the name of the user setpoint PV rather than name of the ophyd object that setpoint is attached to.  But it makes for a 1,000,000 % more useful error message.

fix ophyd's most frustratingly unhelpful error message

---

ophyd/tests/test_bluesky_protocols.py
requirements-test.txt

Adding test which explicitly checks ophyd objects against new bluesky protocols using static analysis. I'm sure there are more objects that could be checked, willing to add if desired.

TST: test against bluesky protocols

---

ophyd/signal.py
ophyd/tests/test_signal.py

In a situation such as
```
In [1]: from ophyd.signal import Signal
In [2]: signal = Signal(name="the_none_signal", value=None)
In [3]: signal.describe()
...
ValueError: Cannot determine the appropriate bluesky-friendly data type for value None of Python type <class 'NoneType'>. Supported types include: int, float, str, and iterables such as list, tuple, np.ndarray, and so on.
```
I would like the exception to report the name of the Signal having a bluesky-unfriendly value.
This PR proposes chained exception handling in `Signal.describe()` to provide that information so the user sees
```
In [1]: from ophyd.signal import Signal
In [2]: signal = Signal(name="the_none_signal", value=None)
In [3]: signal.describe()
...
ValueError: Cannot determine the appropriate bluesky-friendly data type for …
```

report signal name on ValueError in Signal.describe()

---

ophyd/sim.py
ophyd/tests/test_sim.py

Whilst writing some unit tests against devices at DLS I found that `make_fake_device` was failing against `Devices` where I had specified timeouts on creating `EpicsSignals`. Adding the timeouts arguments to `FakeEpicsSignal` fixes this. The modified test should fail on master but pass on this branch.

Added timeout arguments to FakeEpicsSignal

---

docs/source/reference/release_notes.rst
ophyd/areadetector/filestore_mixins.py
ophyd/areadetector/plugins.py
ophyd/areadetector/trigger_mixins.py
ophyd/device.py
ophyd/signal.py
ophyd/tests/test_utils.py
ophyd/utils/epics_pvs.py

The functionality of the free function `set_and_wait(obj, val)` can be better
accomplished via `obj.set(val).wait()` and the existence of this function leads
to confusion.

API: deprecated use of set_and_wait function

---

ophyd/sim.py
ophyd/tests/test_sim.py

See #1041 
* Adds a `FakeEpicsPathSignal` to allow for testing device logic that references an `EpicsPathSignal`

ENH: Added FakeEpicsPathSignal for testing

---

ophyd/status.py
ophyd/tests/test_epicsmotor.py

`MoveStatus` reports a `fraction` starting at 1 and tending towards 0 as the underlying operation progresses toward its goal. You would expect a `MoveStatus` to report a final fraction of 0, but instead it reports a 1. This is because it inherits from `DeviceStatus`, which reports a fraction of 1 as part of its `_settled` hook. 
One class treats `fraction` as "how far have we come?". The other treats it as "how far do we have to go?". This PR takes the behaviour of `MoveStatus` as canonical and modifies `DeviceStatus` in accordance.

Make DeviceStatus report a fraction 0 rather than 1 once complete

---

ophyd/signal.py
ophyd/tests/test_signal.py
ophyd/utils/epics_pvs.py

- Add `InternalSignal` from downstream `pcdsdevices`. This is a utility signal class to be used by devices that want to store data in soft signals but want other code to avoid putting to these signals. We can't prevent other code from interfering, but we can make the intent very clear by declaring that signal as an `InternalSignal` and require an extra `internal=True` kwarg to put or set a new value. I've used this in the past to create in-software `done` signals for positioner classes and `status`-like signals that would be read-only if in EPICS, but cannot be read-only because the device itself does need to be able to update them from python.
- In order to make this work for `set`, I needed to be able to pass the `internal=True` kwarg into `set_and_wait`. This necessitated a cascade of …

ENH: Upstream InternalSignal, allow passing of put arguments through set

---

docs/source/explanations/area-detector.rst
docs/source/reference/release_notes.rst
ophyd/areadetector/detectors.py
ophyd/areadetector/trigger_mixins.py

While talking through how to implement a new area detector (the exspress3 community IOC) in Ophyd, we realized that it would be a lot clearer if we renamed `dispatch` -> `generate_datum`.
If we do not want to deprecate the old name I can drop the last commit.

Rename dispatch -> generate_datum

---

ophyd/ophydobj.py
ophyd/signal.py
ophyd/sim.py

This is part of the May 2022 EPICS Codeathon effort
I've taken all of the `self.log.info` log messages and dropped them to `debug` level.
At LCLS we've instituted a log filter that drops all of these from info to debug because they are too noisy to be useful. Semantically, I take `INFO` to be equivalent to a logged `print` statement, so I claim that anything that would be annoying in a `print` statement should be dropped to `DEBUG` level.
I'm going to talk through each of these calls and why I want to reduce the log level, in case there is disagreement or misunderstanding of use cases:
- ophyd/ophydobj.py
- "first instance of OphydObject: id=%s"
- I'd never put something like this a print statement, it's more of a debug helper for developers. The user doesn't need to care about object ids …

MAINT: reduce log level of spammy self.log.info log messages to debug

---

ophyd/sim.py

In #1044 , we found that the .set_finished() method took some time to resolve, and the returned object would not always be immediately done and successful.  
NullStatus wants to be finished upon creation, so we wait for `set_finished()` to complete at initialization.

MNT: Wait for NullStatus to mark itself as finished

---

docs/source/tutorials/device.rst
docs/source/tutorials/single-PV.rst

In the tutorial, I replaced three instances of `caproto.ioc_examples_random_walk` with `caproto.ioc_examples.random_walk` (changed the underscore between "examples" and "random" to a period).

Fix tutorial typos

---

ophyd/__init__.py
ophyd/pv_positioner.py
ophyd/signal.py
ophyd/tests/test_pvpositioner.py
ophyd/utils/epics_pvs.py

Part of the May 2022 EPICS codeathon effort
Relies on the `InternalSignal` from #1045, which would need to be merged first
- Adds `PVPositionerIsClose`, a helpful PV positioner for when your IOC doesn't supply a `done` signal.
- Adds `PVPositionerDone`, a dummy class for when the user wants their signal to "look like" a motor and cannot be dissuaded.
- split out the "waiting" part of `ophyd.utils.epics_pvs._set_and_wait` into its own standalone utility, `wait_for_value` because I needed it to write a reasonable test

ENH: Upstream helpful PV Positioners, add wait_for_value util

---

ophyd/device.py

This PR proposes a minute change to the DEBUG log output for `stage_sigs` in `BlueskyInterface.stage()` and `BlueskyInterface.unstage()`.
Presently the log output looks like this:
```
2022-05-25 13:17:27,860 - ophyd.objects - device.py:524 - DEBUG - Staging xs3_hdf5plugin
2022-05-25 13:17:28,073 - ophyd.objects - device.py:547 - DEBUG - Setting xs3_hdf5plugin to 1 (original value: 'Enabled')
2022-05-25 13:17:28,075 - ophyd.objects - device.py:547 - DEBUG - Setting xs3_hdf5plugin to 'Yes' (original value: 'Yes')
2022-05-25 13:17:28,076 - ophyd.objects - device.py:547 - DEBUG - Setting xs3_hdf5plugin to 1 (original value: 1.0)
...
2022-05-25 13:17:28,453 - ophyd.objects - device.py:603 - DEBUG - Setting xs3_hdf5plugin back to its original value: 1.0)
2022-05-25 13:17:28,456 - ophyd.objects …
```

Tweak stage_sigs DEBUG logging

---

ophyd/ophydobj.py

`OphydObj.subscriptions`:
* Run once per object instantiation, this can add up to a significant amount of time
* Instead, set once when subclassed

PERF: set subscriptions only once per class

---

ophyd/tests/test_log.py

Per @jklynch this test was meant to check that we have scrubbed `TRACE`-level logs from ophyd. But now one of our upstream deps _is_ using `TRACE`, which causes this test to fail.
I think it's fine to remove this: we shouldn't test against shared global state not under ophyd's control.

Do not assume TRACE is unused.

---

ophyd/sim.py
ophyd/tests/test_sim.py

* Change `SynAxis` to make a `MoveStatus` rather than a `DeviceStatus`.
* Update this status periodically during motion (period is customisation with a constructor parameter, defaults to 6 times per move)
* Example use: progress bars with Bluesky

Make SynAxis produce an updating MoveStatus

---

ophyd/areadetector/filestore_mixins.py

* Capture signal is always triggered even in Single write mode.
* In single mode, the following error message is displayed
```ERROR: capture not supported in Single mode```

Fix capture signal was always triggered

---

ophyd/sim.py
ophyd/tests/test_sim.py

PR #1036 made SynAxis produce a MoveStatus. Unfortunately SynAxisNoPosition inherits from this, but has no position, which is required for MoveStatus. This reverts to using DeviceStatus just for SynAxisNoPosition and adds a test for it
This was spotted in https://github.com/bluesky/bluesky/pull/1542
Credit to @callumforrester for the test

Fix SynAxisNoPosition

---

.github/workflows/docs.yml

#1076 moved the build to build/html, but didn't update the deploy command. This fixes this so it will go live to blueskyproject.io/ophyd

Deploy to the correct place

---

ophyd/utils/paths.py

We had an internal discussion in NSLS-II Slack, and thought it would be more useful/secure to have the default mode of the created directory tree without writing permissions for "others". It's questionable what we should leave for the "group" writing permissions, for now, I set it to `755` (=`rwxr-x-rx`), but open for discussion/arguments.

Change `make_dir_tree` default dir mode to `755`

---

ophyd/status.py

In a similar situation to #1086 , we had an issue where the error message `Status has failed to complete` was not very illuminating as to which status that was, so I have added this information to the `raise WaitTimeoutError` calls in the same manner as it is added to other exception messages in `status.py`. This would be really helpful to us in avoiding wrapping every `wait()` with try/except to record what we are waiting on or subclassing every kind of status we have to modify `wait()` and I hope it might be useful to others too.

Add status repr to WaitTimeoutError message

---

ophyd/tests/test_areadetector.py
ophyd/tests/test_pvpositioner.py

Because it is a bit annoying having to rerun tests all the time, this PR is looking into if we can make it so that we rerun tests less in future.
On another PR I kept getting failures like this one: https://github.com/bluesky/ophyd/actions/runs/4605633309/jobs/8137912252
In the last collaboration meeting it was suggested to move this smoke test to the bottom of the file and see if that changes anything. Either way it would be good to do some investigation here into why the tests are so slow. Perhaps we need to increase the timeout if nothing else can be done?

v2: try to fix some constantly failing tests

---

ophyd/v2/core.py
ophyd/v2/tests/test_core.py

added ._exception to AsyncStatus to match with method in v1 Status object
Solves https://github.com/bluesky/ophyd/issues/1098
This will be followed by a PR in bluesky, which will change the Status object that ophyd v2 AsyncStatus inherits from as well as how FailedStatus gets instantiated. Once I have done this, I will link it here so the changes can be viewed together.

Ophyd v2: add _exception to AsyncStatus to propagate errors through FailedStatus.

---

ophyd/v2/core.py
ophyd/v2/tests/test_core.py
pyproject.toml
setup.cfg

The purpose of this PR is to be able to define v2 Devices with dictionary attributes containing (nested) devices, instead of just plain devices. i.e. something like:
```python
class myDevice(StandardReadable):
def __init__(self, prefix: str, name: str = ""):
self.child1 = DummyDevice("device1")
self.dict_with_children =
{
"abc": DummyDevice("device2"),
123: DummyDevice("device3"),
}
super().__init__(prefix, name)
```
The idea is, that these sub-devices will all be correctly named and connected. With the current master branch, "device2" and "device3" would be ignored (i.e. the devices in the dictionary).
Initially, I allowed a user to create a dictionary as an attribute to a Device, as shown in the code snippet above. This worked OK; standard readable has a set_name and connect method that …

v2: Add dict support

---

ophyd/v2/core.py
ophyd/v2/tests/test_core.py

Tom has noticed that sometimes, wait_for_connection fails quietly. He has fixed this, but in a PR with other things in it. This is a simple PR to isolate that fix.
first commit: copied over wait_for_connection function from ajgdls:pva-dev (PR 1096), and added some tests for it
relates to https://github.com/bluesky/ophyd/pull/1096

propagate errors through wait_for_connection

---

ophyd/v2/core.py
ophyd/v2/tests/test_core.py

resolves https://github.com/bluesky/ophyd/issues/1090
made Device a concrete class rather that ABC, simplified logic in corresponding child classes like StandardReadable and DeviceVector.

v2: make device class concrete

---

ophyd/v2/core.py
ophyd/v2/tests/test_core.py
setup.cfg

Something in the catch-throw-catch-throw cycle was confusing the traceback. Either way, this is clearer. Added a test to check.

v2 Fix traceback of a failed AsyncStatus object

---

ophyd/v2/_aioca.py
ophyd/v2/_p4p.py
ophyd/v2/core.py
ophyd/v2/tests/test_core.py
ophyd/v2/tests/test_epics.py
ophyd/v2/tests/test_epicsdemo.py

simple PR to remove `Monitor` and `SimMonitor` from ophyd/v2/core.py.
It has been agreed that it makes sense if the backend only keeps track of one single callback. Therefore, we no longer need a `Monitor` to keep track of potentially several callbacks.

v2: remove monitor

---

ophyd/v2/core.py
ophyd/v2/tests/test_core.py

Useful for busy record, or other Signals with pattern:
- Set Signal with wait=True and stash the Status
- Read the same Signal to check the operation has started
- Return the Status so calling code can wait for operation to complete
Merge after #1123

v2: Add set_and_wait_for_value()

---

ophyd/v2/epics.py

Using functions means that the enums referencing them do not behave as
expected. eg
def foo(): pass
class Transport(Enum):
a = foo
In this setup, `Transport` will have no member named `a` (only a class
method), and `Transport.a.value()` will raise an AttributeError.

Use classes for fallback epics signal backends

---

.codecov.yml

Fixes https://github.com/bluesky/ophyd/issues/1149

Add .1% threshold for codecov CI

---

docs/user_v1/explanations/status.rst
docs/user_v1/reference/release_notes.rst
ophyd/status.py
ophyd/tests/test_status.py

Fixes #1142.
Adds a stable subscription status that easily allows for checking that a component stays stable for some time. Also, adds docs and tests for it.

ENH: Add a StableSubscriptionStatus

---

ophyd/signal.py

The lowest layer of pv.get accepts a count, which specifies how many array values to return. This count argument was not percolated all the way up the api stack, but was documented.
I require this to be able to retrieve values from a data acquisition device that can have a very large array of results, and the default value (2048) is way too small.

ENH: pass the count parameter along, as already documented.

---

docs/user/how-to/pseudopositioner.md

Someone here at DLS came across a ModuleNotFoundError following the tutorials

Fix typo in docs

---

ophyd/sim.py

When using SynAxis for simulated testing, calling `.describe()` on an instance returns a descriptor for integers rather than floats.
```python
from ophyd.sim import SynAxis
if __name__ == "__main__":
sim_motor = SynAxis(name="motor1", value=3.14)
print(sim_motor.describe())
```
Which produces:
```
OrderedDict([('motor1', {'source': 'SIM:motor1', 'dtype': 'integer', 'shape': [], 'precision': 3}), ('motor1_setpoint', {'source': 'SIM:motor1_setpoint', 'dtype': 'integer', 'shape': [], 'precision': 3})])
```
Declaring the components for SynAxis with a value of `0.0` rather than `0`. Running demonstration code above with the fix in this PR produces:
```
OrderedDict([('motor1', {'source': 'SIM:motor1', 'dtype': 'number', 'shape': [], 'precision': 3}), ('motor1_setpoint', {'source': …
```

BUG: Change declaration of SynAxis components such that describe() works properly.

---

ophyd/areadetector/trigger_mixins.py
ophyd/tests/test_areadetector.py

Fixes the ADTriggerStatus to match the behaviour as documented in https://github.com/bluesky/bluesky/pull/1496/files
Also, added a test for this behaviour.

BUG: Fixed fraction in ADTriggerStatus to match docs

---

ophyd/status.py
ophyd/tests/test_status.py

Here is a merge request that mitigates concern expressed here: https://github.com/bluesky/ophyd/pull/837#discussion_r409007458 (also linked with issue #844).
I have the impression, a simple optimization is to not create a thread if it is not needed (in particular when timeout is set to `None`, which seems to be most of the time).
Otherwise some background about the problem `Status` objects want to solve with the callbacks thread would be insightful.

status: do not create thread to run callbacks if timeout is None

---

ophyd/pseudopos.py

Fix reST syntax in PseudoPositioner

---

MAINTAINERS.md

As discussed in person. This lists the people that are maintainers on ophyd

DOC: Create MAINTAINERS.md

---

ophyd/quadem.py

Somehow, this missed testing.  A long time ago.
```py
tetramm = TetrAMM("8idTetra:QUAD1:", name="tetramm")
for axis in "x y".split():
for attr_name in "offset offset_calc scale".split():
getattr(tetramm, f"position_{attr_name}_{axis}").kind = "config"
AttributeError: position_scale_y
```

TYPO should be lower case to be consistent with others in this module

---

setup.cfg

Related to https://github.com/bluesky/bluesky/pull/1813. As I said over there:
> Should we double our CI matrix to test against numpy 1.x and 2.x? I lean "no", it is good enough to test against latest numpy, particularly because bluesky itself does not have any deep numpy integrations or compiled code directly in ophyd.

Unpin numpy

---

.github/workflows/code.yml

This adds a single build to the matrix that tests against prereleases of bluesky and event-model.
Relevant section of GH Actions docs: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#example-adding-configurations

Test on prereleases of bluesky, event-model.

---

ophyd/device.py
ophyd/tests/test_device.py

- close #1218
Tested identical change locally at APS as part of https://github.com/aps-8id-dys/bluesky/issues/95 and https://github.com/aps-8id-dys/bluesky/issues/99.

use provided value of trigger_value

---

.github/workflows/code.yml
docs/user/reference/release_notes.rst
ophyd/tests/test_issue944.py
pyproject.toml
pytest.ini
scripts/epics_docker.sh

For reasons not yet understood, these images now have 0 size on dockerhub

CI: do not try to start docker images that no longer exist

---

.github/workflows/code.yml
.github/workflows/docs.yml
.gitignore

The release job for v1.10.0 failed: https://github.com/bluesky/ophyd/actions/runs/12150016130/job/33881909125. Attempting to fix it here.
Closes #1216
Closes #1223

CI: update release process

---

ophyd/_dummy_shim.py

See the issue for discussion.
Is there a static list of supported control layer "shims" I can use for the error message?
Closes #1225

Add messages to dummy control layer NotImplementedError to install either pyepics or caproto

---

.pre-commit-config.yaml
ophyd/signal.py
ophyd/tests/test_signal.py
setup.cfg

Not all serializers (e.g. orjson) will fallback to the float behavior.

FIX: do not leak the book-keeping float sub-class out of __init__

---

docs/user/explanations/status.rst

When you use subscription status you almost never want the subscription to run immediately when you instantiate it. The docs have caused us a number of problems with people copying the example and seeing multiple values in their readings when a trigger executes at a time they don't expect. 
I changed the example to fit what is commonly done (in my experience)

Update status.rst SubscriptionStatus example

---

ophyd/device.py
ophyd/tests/test_device.py

In trying to set up integration tests for a beamline profile with many connections, I ran into a timeout error waiting for a device to connect. The default of 2 seconds is too low so I bumped it up to 10 seconds.
I also added the ability to configure this for individual `Component`s that may have many sub-`Component`s that try to connect at the same time.
The timeout occurred [here](https://github.com/bluesky/ophyd/blob/main/ophyd/quadem.py#L119-L121). It was running on a single locally hosted IOC that [accepts all connections and returns 0 for everything](https://github.com/NSLS2/gha-beamline-integration-test/blob/2025-1.0-test/spoof_beamline.py).

Added ability to configure wait_for_connection timeout

---

ophyd/areadetector/plugins.py

Flake8 errors:
```
ophyd/areadetector/plugins.py:92:5: F824 `global _plugin_class` is unused: name is never assigned in scope
ophyd/areadetector/plugins.py:2726:5: F824 `global _plugin_class` is unused: name is never assigned in scope
```

Remove unnecessary global _plugin_class usage

---

setup.cfg

A new release of caproto is breaking functionality with the `_caproto_shim.py`. We should avoid v1.2.0 for the time being.

Incompatiblity with caproto v1.2.0

---

ophyd/device.py
ophyd/signal.py
ophyd/tests/__init__.py
ophyd/tests/test_timeout.py

See #1242 for a description of the issue that this PR solves.
In addition to the bug fix, we also add the ability to set default class-wide connection timeouts for `Device`s as well as individual `Device`s. This is the amount of time it takes for all sub-devices or signals to connect.
This is mirrored by the `EpicsSignalBase.set_defaults` method to set class-wide connection timeouts.
```python
from ophyd.device import Device
Device.set_defaults(connection_timeout=20.0)
```
```python
from ophyd.device import Component, Device
class MyDevice(Device):
sub_device = Component(Device, "Device:", connection_timeout=10)
```
Closes #1242

EpicsSignalBase connection timeout fix + Device connection timeout

---

ophyd/_caproto_shim.py
setup.cfg

NOTE: To be merged after (and only if) https://github.com/caproto/caproto/pull/862 is merged and released.
Uses the default context as a cached class method rather than the instance method that was released in https://github.com/caproto/caproto/releases/tag/v1.2.0
It also ensures that a different context is not passed in to the `get_pv` function so that the same context is used by caproto as is used by the event dispatcher.
Ophyd can't make its own default context unless it overrides and monkey-patches the remaining `pyepics_compat` functions. We only override `get_pv` right now: https://github.com/bluesky/ophyd/blob/be3a5143beeb23cc7ece4abc6285197cc00af391/ophyd/_caproto_shim.py#L188-L189
Please let me know if I am missing something here!

Fix use of default context in caproto shim

---

ophyd/areadetector/plugins.py

The changes are extracted from ADCore repo,
```
git diff -r R3-4...R3-5 ADApp/Db/NDPluginBase.template
git diff -r R3-4...R3-5 ADApp/Db/NDFileHDF5.template
...
```

add R3-5 version plugins
